### ISSUE TITLE
New blob_path_prefix spec metadata field in Azure Event Hubs binding spec

### ISSUE THREAD

**Issue by TalalMahmoodChaudhry** [dapr/components-contrib#1127]
# Current Behavior
Event Hub Binding Spec does not distinguish its checkpoint files (there's one per partition) in the container to work across multiple Event Hubs, a separate storage container is needed for each Event Hub.

# New Behavior with Feature
Add a new field `blob_path_prefix` in the spec metadata field. This way one container can be used for multiple Event Hub Bindings.

# Release Note

RELEASE NOTE: **ADD** New feature in Dapr - Azure EventHub Binding spec.

**Comment by CodeMonkeyLeet** [comment]
This is not currently controlled by the Event Hubs bindings component in Dapr today. That component relies on the `azure-event-hubs-go/v3` SDK provided `NewStorageLeaserCheckpointer`, which only takes the container name and encapsulates creation and management of the checkpoint files.

For Dapr to independently support this feature, it would need to implement its own `LeaserCheckpointer` so that it could continue to use the `EventProcessorHost` from the Event Hubs go SDK, which is probably going to be more difficult to maintain over time.
