### ISSUE TITLE
Add logic to utilize sqs/sns fifo queues and topics with dapr pubsub

### ISSUE THREAD

**Issue by mhozhda-agiliway** [dapr/components-contrib#1205]
After some research and discussion on discord it occurs there is currently no possibility to use AWS SQS/SNS FIFO queues/topics with dapr pubsub component. By default dapr creates standard queues and topics. And if I try to specify the name of existing FIFO topic (e.g. 'mytopic.fifo') it creates new topic named 'mytopicfifo' as nameToAWSSanitazedName method from snssqs.go  just deletes dot as not allowed symbol while AWS requires FIFO queues and topics to have .fifo suffix

It would be great to have a possibility to utilize AWS FIFO topics and queues with dapr pubsub component

**Comment by olitomlinson** [comment]
Is there an opportunity to make a generic setting here that may work for different broker implementations?

I ask because there is no `enable FIFO` switch in Azure Service Bus like there is in AWS (such as by appending `.fifo` to the end of a queue name)

The way to enable FIFO/Ordered messages in Azure Service Bus is by using a [Session ID](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions) which I believe is an equivalent concept to the [Message Group ID](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagegroupid-property.html) in AWS SQS.

Maybe it makes sense to build a FIFO concept around this? I think there may be an extra advantage here in that it won't preclude a competing consumer model. I believe just appending `.fifo` does limit concurrency of consumers to just once. Full disclaimer : I'm no AWS expert )

**Comment by amimimor** [comment]
I'll jump in (late) and add that the created queue name is anyways dependent on the `Subscription` (either dynamic or preconfigured in yaml) defined and is set to the `AppName` of the consumer, so adding of `.fifo` is pointless in the sense that it is not expected that someone would call their application `myservice.fifo` just to trick the system to use SQS FIFO. However it is a interesting problem to try tackling of what is favorable: either adding a generic configuration to PubSub components to have FIFO settings or just add something in the spirit of `enableFifo` configuration for Azure Service Bus and AWS SQS. In case we want to start with the later, I'll be happy to jump in as we already wanted to add this ability to daprd

**Comment by yaron2** [comment]
@olitomlinson @amimimor I think it'd be valuable to add FIFO as a concept. Granted, not all implementations will support this and so I favor an implementation specific (yet consistently named) `FIFO` metadata item that will provide a hint to the component to use FIFO if possible.

**Comment by olitomlinson** [comment]
@yaron2 

do you see this metadata property going down a boolean switch route 

i.e. `"FIFO": true` 

or a string in which to specify a SessionID | MessageGroupID 

i.e. `"SessionId" : "r9i203i0r3"`

**Comment by yaron2** [comment]
> @yaron2
> 
> do you see this metadata property going down a boolean switch route
> 
> i.e. `"FIFO": true`
> 
> or a string in which to specify a SessionID | MessageGroupID
> 
> i.e. `"SessionId" : "r9i203i0r3"`

Personally, I prefer `"FIFO: true"`.

**Comment by olitomlinson** [comment]
@yaron2 

> and so I favor an implementation specific (yet consistently named) FIFO metadata item

> Personally, I prefer `"FIFO: true"`

Not sure this will work, as I described above Azure Service Bus doesn't have a concept of enabling FIFO / ordered delivery with a Boolean so the consistency that you're after can't be achieved. Unless I'm missing something?

Maybe a FIFO object, would be better so then it can be extended to support a Session ID / Message Group ID in the future

```json
 "fifo" : { 
    "enabled" : true,
    "sessionId" : "r9i203i0r3"
 }

```

At which point `sessionId` becomes optional for AWS SQS but mandatory for Azure Service Bus.... hmm...

**Comment by jjcollinge** [comment]
@olitomlinson FYI, I was looking to enable session support in ASB soon in a similar way to how the Azure Functions trigger works i.e. you can use a boolean operator like `enableSessions` and we provide a mechanism to handle each session in order (see here for details: https://github.com/dapr/components-contrib/issues/289). It's not a perfect mechanism and I was planning to also allow the consumer to specify a list of session ids that they want to explicitly listen to too. I haven't had time to really think about this generic FIFO capability so I'll respond once I've given it some thought.

**Comment by jjcollinge** [comment]
Regarding the common FIFO discussion, I guess my first question is, does trying to use common metadata for FIFO provide a valuable abstraction? If the Dapr runtime has to read the metadata value to do something outside the context of the specific pubsub provider then having a consistent metadata name makes sense, however, I don't think that's the case here? I think this metadata value will only be read in the specific pubsub implementation. Another reason might be to reduce the tax of changing config between components. However, you already have to change the component metadata between SQS and ASB anyway so are we really making much of a saving? Is there anything else we can think of? @yaron2 I wonder if you had some more thoughts on this?

My thinking around how I'd do this in ASB would be a metadata property along the lines of what @olitomlinson shared:
```go
type sessionsMetadata struct { 
    enabled bool, // Flag to indicate the intention to use sessions (could be inferred but would rather be explicit).
    ids []string // List of session ids - if empty and enabled, dynamically subscribe to sessions.
 }
```
If there is a useful abstraction for FIFO I'd be happy to try and align this with the SQS implementation. For now, I'll stop hijacking this thread for ASB relation discussions 😄.

@olitomlinson I'm not sure I understand this comment below - could you please clarify?

"Anyway, my concern with this particular GH issue is that by not allowing the publisher provide an application-centric session Id, how can FIFO / ordered messaging ever be achieved with ASB in Dapr"

**Comment by olitomlinson** [comment]
> I'm not sure I understand this comment below - could you please clarify?

> "Anyway, my concern with this particular GH issue is that by not allowing the publisher provide an application-centric session Id, how can FIFO / ordered messaging ever be achieved with ASB in Dapr"

In the application code, which is about to publish to the topic, there needs to be a way to specify the Session ID / Message Group Id. I'm assuming that would be done by setting a new metadata property here :

https://docs.dapr.io/reference/api/pubsub_api/#metadata

...so a new property `metadata.sessionId` alongside the existing `metadata.ttlInSeconds` and `metadata.rawPayload` 

This would then form the basis for a PubSub component _implementation agnostic_ way of setting FIFO / Message Ordering, which should work across ASB and AWS, and possibly others, maybe? 

IMO it makes sense to rule out this approach first, rather than relying on implementation-specific metadata to light-up FIFO in different ways for different implementations.

A big attraction of Dapr for me is to be able to swap out AWS SQS for ASB through the component definitions (to support many different cloud vendor environment of my companies forth coming product) without having to make application-level code changes and vendor-specific builds.

All I'm alluding to with all of this is that it may be possible to commit to a PubSub component level abstraction around Message Ordering / FIFO.

**Comment by jjcollinge** [comment]
Understood, thanks. The change to allow setting the sessionId in request metadata for ASB has already been merged and will be available in v1.5 but there's nothing stopping us adding support for this in SQS if we decide it is useful. It's good to discuss these things so appreciate your thoughts. I'll have a think about the common metadata a little more and get back to you. 👍

**Comment by olitomlinson** [comment]
I appreciate the discourse, and hopefully this might help shape the future somewhat :)

**Comment by amimimor** [comment]
I'm becoming available to implementing the aforementioned feature. Have we gone into conclusion about structuring of the metadata? 

Regarding the concept of Message Group ID ("MGI") in SQS FIFO, as mentioned here, it only applies to ordering of publisher messages belonging to a particular MGI. However, if there is just one MGI, it limits the consumption to a single consumer at a time (no concurrency even if there are multiple consumer instances). Meaning is that AWS keeps a 1:1 ratio between the number of MGI (producers) and *concurrent consumers*. For more details [check this AWS blogpost out](https://aws.amazon.com/blogs/compute/solving-complex-ordering-challenges-with-amazon-sqs-fifo-queues/) 

I also want to highlight the fact that a publisher publishes messages to an SNS topic, not an SQS (FIFO) queue, so the metadata for using fifo effectively creates both an SNS FIFO and SQS FIFO (with subscription connecting them).

Furthermore, when using SNS FIFO, one can enable an automatic message deduplication feature, or provide a message ID of some sorts and instruct SNS to deduplicate, based on that ID.
