### ISSUE TITLE
All Azure components should support Managed Identity auth

### ISSUE THREAD

**Issue by skwasiborski** [dapr/components-contrib#130]
Currently all secret stores and by extension other components require some kind of in cluster secrets. It would be great if it would be possible to use Azure Manage Service Identity where possible.

Currently I see following possible places to use MSI:
- keyvault secret store
- cosmos db binding
- blobstorage binding
- eventhub binding
- servicebus binding
- azureservicebus pub/sub
- cosmos db state store

**Comment by mkosieradzki** [comment]
Especially keyvault… is a MUST have. Otherwise this secret store makes no sense.

**Comment by yaron2** [comment]
@mkosieradzki there's already a PR for it: https://github.com/dapr/components-contrib/pull/185

**Comment by msfussell** [comment]
Managed Identity for authenticating with KeyVault is done. @skwasiborski can you describe the scenarios more for the other bindings?

**Comment by AaronCrawfis** [comment]
All Azure components should support managed identities. The behavior should be a simple `useManagedIdentity:true` component spec option that tells the binding to init with the managed credential from the underlying platform instead of connectionStrings. This behavior should work on Azure Kubernetes Service using either [cluster identity](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity) or [pod identity](https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity).

For self-hosted Azure VM machines it should use https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-windows-vm-ua-arm

Not sure if Go supports it, but in dotnet you can also prompt for user credentials and use that token if you're running locally and want to debug against an Azure Resource without a connection string.

**Comment by jjcollinge** [comment]
I've been meaning to add this for Azure Service Bus PubSub - I will open a separate issue and PR next week.

**Comment by AaronCrawfis** [comment]
@dapr/maintainers-components-contrib can you please triage this so it's not closed

**Comment by codesmon** [comment]
I see this has been closed. For our project the ability to use MSI to access the Cosmos State (and Actor state) stores, and ServiceBus as critical to out continued use of Dapr. Would it help for me to split these out into separate issues or can this be reopened?

**Comment by AaronCrawfis** [comment]
> @dapr/maintainers-components-contrib can you please triage this so it's not closed

 @dapr/maintainers-components-contrib

**Comment by ebc92** [comment]
This issue is still closed but it is still applicable as far as I can tell. This is a much desired feature for my team & organization (azure servicebus & cosmosdb specifically). Please consider once more reopening this issue.

**Comment by berndverst** [comment]
We will be doing this work as part of certifying Azure components as stable. In some cases we depend on the new Azure SDKs being ready.

There will be no specific work to resolve this issue, instead follow each Azure components certification tracking issue. You may also want to follow issues for the Azure SDK upgrades like #1532.

If we support any form of AAD like service principal we get support for Managed Identity automatically for free the way our code works.

In general we will support AAD auth for every Azure service that provides a way to authenticate with AAD. This is one of the criteria for the components to be considered stable.
If the Azure SDK we are using however does not support AAD we may proceed without this feature and will revisit at a later time as soon as the underlying SDK supports it.

cc @ItalyPaleAle who is leading our migration to the new Azure service SDKs.

**Comment by berndverst** [comment]
@codesmon Cosmos DB state store supports authentication with AAD for several releases. The relevant code is here: https://github.com/dapr/components-contrib/blob/master/state/azure/cosmosdb/cosmosdb.go#L134

Looks like we forgot to document this here:
https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-azure-cosmosdb/

You can follow these instructions:
https://docs.dapr.io/developing-applications/integrations/azure/authenticating-azure/

I don't think we need to keep this general issue open @AaronCrawfis @yaron2 because it really is part of the standard to certify as stable Azure components. Cosmos DB is a bit weird because it was grandfathered in, but it already does support it.

**Comment by rzyns** [comment]
Are there any plans to support managed identity auth in the rest of the Azure components? Specifically, I'm looking for support in either the Event Hubs binding or the Storage Queues binding so I can port an existing application to Dapr

**Comment by berndverst** [comment]
@rzyns as of release 1.8 Azure Storage Queues binding has AAD support. Apparently we forgot to update the docs - but it works the same way as with the other components supporting AAD - same metadata fields etc.

**Comment by berndverst** [comment]
I believe all components which can support AAD now have AAD support implemented. At this time I will close this issue. We will always implement AAD support if this is possible with the official SDKs we are provided.
