### ISSUE TITLE
Azure Service Bus - Sidecar and main container can’t interoperate after a long period of time(3-4 weeks)

### ISSUE THREAD

**Issue by T-REX-XP** [dapr/components-contrib#1414]
## In what area(s)?
 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release
## What version of Dapr?
> 1.3.x

## Expected Behavior
- Communication between the main container and their sidecar should work all time, even if any messages don't send for a long time. 
- It will be great to see logs in case binding to Azure Service Bus has been broken

## Actual Behavior
Does anyone faced with a situation when the sidecar and main container can't interoperate anymore??
I mean, after a long period of time(3-4 weeks) the app container can't receive any service bus message. Only restarting the pod fixing the problem. But, again the logs of the main container and sidecar do not contain any helpful info regarding that issue. Also, I can't see any extra metrics such as pod restart count, etc, so it seems like the main container work fine.

I'm using Azure Kubernetes Service, Azure Service Bus, and services that are based on DOTNET 5, DAPR 1.3.

**Comment by jjcollinge** [comment]
In relation to @R-Lamberson's issue with ASB pubsub publish - I'd suggest that this is because we currently cache the publish topics indefinitely, if the connection is idle for a while and reset by the peer then this connection is dead but we don't recreate it and will attempt to use it. We can add either a TTL to the cache or I think a better solution is to handle the connection reset error explicitly and recreate the connection. I can look at doing this tomorrow. However, I don't believe this is relevant to the original issue which concerns the ASB binding.

**Comment by T-REX-XP** [comment]
> please confirm if this issue is with the ASB binding or the ASB pubsub component?
Yes, I can confirm that we are using the component with type binding.
`type: bindings.azure.servicebusqueues`

**Comment by R-Lamberson** [comment]
@yaron2  @jjcollinge  I upgraded 1.5.1 and I am getting similar behavior but a new error message - see open issue #4031

I agree that having the dapr client handle the connection error would be more seamless, however is there a way I can handle recreating / resetting the dapr client when I get a connection state like this?
