### ISSUE TITLE
Write ASB Binding v2 using new Go SDK

### ISSUE THREAD

**Issue by jjcollinge** [dapr/components-contrib#1434]
The Azure Service Bus SDK currently used in the Azure Service Bus Binding component is now (as of 2021-11-12) considered deprecated in favor of the new SDK. The new Go SDK is currently in preview but is preparing for GA. There is a migration guide which can be used to assist in the migration. I propose that we plan to write a new ASB binding component (v2) using the new SDK assuming we can achieve feature parity. Once written we can release it as `alpha` whilst we wait for the new Go SDK to reach a stable v1.0.0. I will try find time to investigate this soon.

There is a similar issue for ASB Pubsub component: #1309

**Comment by halspang** [comment]
I've starting working on this and the pubsub issue as part of the certification efforts for the binding. They're coupled in Dapr since they share the same libraries and you can't update one without the other.

**Comment by halspang** [comment]
This shouldn't have been closed. @artursouza - Can you reopen/pin this?

**Comment by berndverst** [comment]
This is a dupe of our new consistent tracking issue #1531. I'm in favor of keeping that issue open instead because we have several such consistent issues open. We also use those issues to track any requests from the upstream SDK teams.

We haven't yet agreed on the versioning policy for our components that use new SDKs. Currently we are not leaning towards a v2 component launched as alpha.

@jjcollinge @yaron2 please see all issues with the prefix `[Azure][Track 2]` for the work to switch them to the new SDKs. Thanks!

**Comment by berndverst** [comment]
I'll add one final comment - @jjcollinge the new SDKs aren't considered stable yet (though are probably close to that). So migration to those SDKs may still be premature.

We (at Microsoft) will migrate components as soon as we deem the new SDKs to be ready. This is also our standard for certifying components as stable. Existing stable components will be updated as soon as the SDKs are ready.
