### ISSUE TITLE
OAuth 2.0 through middleware

### ISSUE THREAD

**Issue by Haishi2016** [dapr/components-contrib#155]
Dapr allows custom middleware to be plugged into the sidecar processing pipeline. Dapr uses middleware for distributed tracing as well as CORS control. And this proposal proposes supporting OAuth 2.0 authorization through the same mechanism. 

When processing a request, the middleware will check for a previously generated random state exists. If not, it generates a new random state and redirect the client to the configured authorization server. If the state exists, it use the code returned by the authorization server to exchange for an access token. Then, it inserts the token to a configurable header name before it passes the request to a downstream handler.

As the authorization server needs to post back the access token from a redirect URL, it's required that the redirect URL points to the Dapr sidecar endpoint. 

Certificate management/configuration is considered out of the scope of this middleware. The middleware requires the Dapr sidecar endpoint has been configured with a proper certificate to allow HTTPS.

**Comment by anuragprafulla** [comment]
@Haishi2016 I would like to take this up if it's available.

**Comment by yaron2** [comment]
I believe this is already done. Haishi can we close the?

**Comment by mkosieradzki** [comment]
There are two problems with this middleware:
1. AFAIK dapr does not support storing sessions in a distributed session state backed by a state store (at least yet) and subsequent calls to this middleware will lead to breaking the session, unless the IDP supports non-interactive, cookie based re-authentication, but even then due to the nature of 302 the verb might get changed from GET to POST and you might loose the payload as well.
2. It is fairly impractical for APIs as it works on 302 redirects (as opposed to 307) and might require interactivity - so it will work great for example plain old websites, but not for the API calls.

@Haishi2016 do you have a specific use case in mind? E.g. server side rendered dashboard?

**Comment by msfussell** [comment]
@Haishi2016 - can you clarify exactly what needs to be done and the scenario for this?

**Comment by msfussell** [comment]
@Haishi2016 Following up here?

**Comment by Haishi2016** [comment]
Sorry for the late response. On @mkosieradzki's comments: 1) the session provider we use does support external session store. We need to improve on docs to explain how to configure those and provide necessary configuration surface. 2) As far as I understand it 307 is not a good practice for the oAuth workflow, as it's subject to impersonation attacks. 

I propose we close this issue and follow up in @jjcollinge's auth and policy proposal and address related issues in that effort.
