### ISSUE TITLE
[pubsub-pulasr] Pulsar namespace setting is invalid

### ISSUE THREAD

**Issue by saber-wang** [dapr/components-contrib#1659]
1.6.0 up 1.7.0
created producer  does not use a namespace
```
time="2022-04-11T01:37:21.575456241Z" level=debug msg="creating producer for topic testEvent, full topic name in pulsar is persistent://public/mcrp-production/testEvent" app_id=mediinfo-mcrp-yanfa instance=test-3.0.94-7c84798747-5dfql scope=dapr.contrib type=log ver=1.7.0
time="2022-04-11T01:37:21Z" level=info msg="[Created producer]" cnx="10.0.199.32:38536 -> xxxxxx:30205" producerID=1 producer_name=pulsar-mini-373-115 topic="persistent://public/default/testEvent"
```
I suspect the tenant settings have also failed -_-

**Comment by shubham1172** [comment]
The issue looks to be due to passing `req.Topic` instead of `topic`. The latter contains tenant and namespace information too.

https://github.com/dapr/components-contrib/blob/03e0c667baafc27ff99ce00d4122084421f15381/pubsub/pulsar/pulsar.go#L181-L184

It was changed in https://github.com/dapr/components-contrib/commit/00c99a4027de26b393a2c087767628d7e150675b

@saber-wang do you want to send in a fix?

**Comment by shubham1172** [comment]
This will be a small fix but is high priority for pulsar users.

**Comment by saber-wang** [comment]
@shubham1172 I can do this
