### ISSUE TITLE
Include IOT hub Test in Azure EventHub Certification test

### ISSUE THREAD

**Issue by surenderssm** [dapr/components-contrib#1664]
Currently the test for IOT hub is commented out and integration with simulation of device sending messages to IOT hub is pending.

Is it a pre req that ./send-io-device-events.sh is run before this test ?
- Yes

Can that logic be pulled into this test and be setup in a step here?

- Yes that's one option, second option is to pull this as part of `github workflow`. Option one sounds closer to test, will give it a shot.

_Originally posted by @surenderssm in https://github.com/dapr/components-contrib/pull/1623#discussion_r837676418_

**Comment by berndverst** [comment]
Hey, so the test isn't commented out -- there is just a different build flag for it.

Take a look at the integration test GitHub workflow which specifically sets this build flag. That should already mostly do what we want.

The problem is that today this test isn't automatically scheduled. Not sure what state was in but please continue the investigation there.

**Comment by surenderssm** [comment]
This has been taken care in #1623
