### ISSUE TITLE
PubSub Component for IBM MQ

### ISSUE THREAD

**Issue by berndverst** [dapr/components-contrib#1672]
Add new IBM MQ PubSub component.

This library likely should be used in the implementation:
https://github.com/ibm-messaging/mq-golang

RELEASE NOTE: **ADD** New IBM MQ PubSub component.
Docs Issues: Needs a PR at time of code check in https://github.com/dapr/docs/issues/2408

**Comment by berndverst** [comment]
We will also need to create conformance tests right away.

**Comment by berndverst** [comment]
For local testing and for the conformance test itself the IBM MQ docker image can be used:
https://developer.ibm.com/tutorials/mq-connect-app-queue-manager-containers/#step-2-get-the-mq-in-docker-image

**Comment by artursouza** [comment]
[MQ Golang](https://github.com/ibm-messaging/mq-golang) requires CGO and the MQ library installed at the dev machine and daprd container image - this is not allowed in dapr sidecar because it would increase our footprint by installing multiple libraries into the container image.

@amulyavarote  is now exploring an alternative where Kafka is used instead and events from IBM MQ are copied via [mq source](https://github.com/ibm-messaging/kafka-connect-mq-source).

Alternatively, a 3rd party could fork dapr/dapr and create an image for daprd that is purposely built to include IBM MQ.

**Comment by artursouza** [comment]
I wonder if IBM MQ could work with our existing MQTT pubsub component:

https://www.ibm.com/docs/en/ibm-mq/8.0?topic=telemetry-mqtt-publishsubscribe-applications

**Comment by berndverst** [comment]
This can stay closed, but we are currently evaluating whether the existing MQTT component works with IBQM MQ with the Telemetry Service enabled which should be MQTT compatible.

**Comment by artursouza** [comment]
We should have an outcome for this first. Also removing this from a milestone.

**Comment by artursouza** [comment]
With pluggable components in 1.9, I wonder if someone from the community would like to implement one as an example.

**Comment by berndverst** [comment]
From an OSS maintainer perspective the outcome is that anyone get build a pluggable component based on this. We should not track pluggable component issues and request in the contrib repo.

Where should those go? Can this be transferred?
