### ISSUE TITLE
Azure Service Bus Component: MessageID isn't guaranteed to be unique

### ISSUE THREAD

**Issue by clemensv** [dapr/components-contrib#1892]
The MessageID in Service Bus is a user-settable field that is not guaranteed to be unique and the service doesn't do anything to enforce uniqueness unless the user explicitly turns on duplicate detection. 

In the underlying AMQP protocol, message-id is optional and therefore cannot be relied on as a key as used here, especially when messages originate from outside of DAPR. See https://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-properties

The "SequenceNumber" system property (see https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sequencing and https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-protocol-guide#message-annotations) is a reliable identifier for uniqueness for a message within the scope of an entity and within the assumed lifetime scope of the lookup table. 

@ItalyPaleAle

**Comment by artursouza** [comment]
Can you clarify the scenario you are targeting here?

**Comment by clemensv** [comment]
I am reading the code and am seeing the use of a value that isn't guaranteed to be unique used as a hashtable index and that is a bug

**Comment by ItalyPaleAle** [comment]
@clemensv thanks for pointing that out. Can you share a link to the line you're referring to?

**Comment by jjcollinge** [comment]
Thanks @clemensv. @ItalyPaleAle the message ID is being used to track the active messages [here](https://github.com/dapr/components-contrib/blob/91ce3d3baf846a34ef6678964ee9f793c9172728/internal/component/azure/servicebus/subscription.go#L321) which is used to renew the locks on any messages we are currently handling. The use of a map here is so that we can do simpler random deletes when a message has been processed. We should move this key over to a guaranteed unique value e.g. sequence number to avoid messages overriding each other.

**Comment by ItalyPaleAle** [comment]
Thanks for explaining @jjcollinge and for the PR :)
