### ISSUE TITLE
Pass kafka record key and other metadata to pubsub subscribers

### ISSUE THREAD

**Issue by ctoomey** [dapr/components-contrib#2213]
## Describe the feature
Currently kafka pubsub subscribers only get passed the kafka record value (payload), record headers, and topic.

Many non-dapr kafka consumer applications make use of other information that's not provided to dapr subscribers: record key, partition #, offset #, timestamp, timestamp type. These are all available when consuming from kafka using kafka's SDKs, e.g, Java's [`ConsumerRecord`](https://javadoc.io/static/org.apache.kafka/kafka-clients/3.3.1/org/apache/kafka/clients/consumer/ConsumerRecord.html).

This additional metadata could be added to the event metadata sent to subscribers that's currently just populated with record headers. Optionally, passing this additional info could be made an opt-in feature requiring subscribers to set a flag in their subscription yaml file.

This change should also be made to the kafka input binding unless for some reason that's not supposed to have feature parity.

## Release Note

RELEASE NOTE: **ADD** Pass kafka record key and other metadata to pubsub subscribers

**Comment by berndverst** [comment]
Sounds like what is required here is:

During the Kafka PubSub subscription handler additional information should be added to the cloudevent JSON.

Related / Required but a larger scope than this issue here:
Only as of this coming release can additional metadata fields be passed through Dapr PubSub via gRPC (HTTP was supported already) [this applies to all components], however note that no SDK has support for reading this data natively at this time (the mapping between incoming gRPC request to SDK native object is a manual mapping at this time which would need to be updated).

Please feel free to open a PR for the desired Kafka data:
You can see messages headers are set as metadata here. Any additional properties would also need to be added to the map of metadata.
