### ISSUE TITLE
Add support for TTL in state stores for all relational databases

### ISSUE THREAD

**Issue by berndverst** [dapr/components-contrib#2288]
Add support for TTL for all relational databases.

Use the native TTL features where possible, and otherwise simulate in Dapr.

To update:

- [X] CockroachDB: #2618
- [X] MongoDB: #2535
- [x] MySQL: #2641
- [X] PostgreSQL: #2302
- [x] Azure SQL Server: #2682
- [X] SQLite

**Comment by ItalyPaleAle** [comment]
In relational databases, we should be able to emulate TTL for state stores fairly easily. Here's how it will work:

- A new "expire_at" column (name can be changed depending on conventions for that database) is added to the table storing data which contains the time the record expires at.
  - The data type depends on what the database supports. If the database has native datetime types, it will use that. Otherwise, a bigint storing a UNIX timestamp can work.
  - A value <= 0 means the record never expires
  - The default value is 0
  - The column will have an index to speed up purging
- When a record with a TTL is added, the database adds the TTL (in seconds) to the current time and stores that for the "expire_at" column
  - Note that the value for "expire_at" MUST be computed in the database (e.g. the query to insert the value would be something like "CURRENT_TIMESTAMP + ttl", so the database computes the current timestamp). This is to avoid issues with potential clock skews.
- When a record is queried, a new WHERE clause is added to the query to make sure that records are returned only if "expire_at" is <= 0 OR "expire_at" < CURRENT_TIME (the time must use the database's clock, to avoid issues with clock skews). Records that have expired are thus silently ignored.
- A background goroutine will periodically purge expired records by running a query like `DELETE FROM table WHERE expire_at > 0 AND expire_at < CURRENT_TIME`.
   - The interval will be configurable via a metadata option
   - The default value can be fairly high, for example 10 minutes (since expired records are silently ignored anyways)
   - If the interval set in the metadata is <= 0, then there's no background garbage collection. This can be used by developers who are sure that they will not use TTLs.

**Comment by ItalyPaleAle** [comment]
Interestingly, looks like the Oracle state store already implemented TTLs in pretty much the same way described above.

**Comment by berndverst** [comment]
@ItalyPaleAle do you plan to run DB migrations (with ALTER table statements) to add the `ttl` column?

**Comment by ItalyPaleAle** [comment]
Yes. Although because we don't keep a `migrations` table today, it may need to do some stuff to see if the column already exists.

**Comment by olitomlinson** [comment]
> Note that the value for "expire_at" MUST be computed in the database (e.g. the query to insert the value would be something like "CURRENT_TIMESTAMP + ttl", so the database computes the current timestamp). This is to avoid issues with potential clock skews.

Also, can we consider offering two types of TTL
- fixed TTL - once the TTL is set, it is immutable.
- Sliding TTL (the TTL period is reset upon modification of the row)

> When a record is queried, a new WHERE clause is added to the query to make sure that records are returned only if "expire_at" is <= 0 OR "expire_at" < CURRENT_TIME (the time must use the database's clock, to avoid issues with clock skews). Records that have expired are thus silently ignored.

FYI This is semantically the same as how Azure CosmosDb handles TTL expiry - even if the physical deletion process lags behind, the API only returns correct data.

> Deletion of expired items is a background task that consumes left-over [Request Units](https://learn.microsoft.com/en-us/azure/cosmos-db/request-units), that is Request Units that haven't been consumed by user requests. Even after the TTL has expired, if the container is overloaded with requests and if there aren't enough RU's available, the data deletion is delayed. Data is deleted once there are enough RUs available to perform the delete operation. Though the data deletion is delayed, data is not returned by any queries (by any API) after the TTL has expired.

**Comment by ItalyPaleAle** [comment]
I believe the current behavior when updating a document with a TTL is that if TTL is not set, the default TTL is applied (resetting any previous TTL).

**Comment by olitomlinson** [comment]
@ItalyPaleAle That sounds like you are describing a sliding/relative TTL?

I wonder if this sliding/relative behaviour needs making more explicit on this page, as I'd say it could be ambiguous.

https://docs.dapr.io/developing-applications/building-blocks/state-management/state-store-ttl/

**Comment by ItalyPaleAle** [comment]
My source is here, based on the Oracle state store that already implemented this change: https://github.com/dapr/components-contrib/blob/d8c2ce47fdb49db8e9ba3ad825d0f9492c0e6f27/state/oracledatabase/oracledatabaseaccess.go#L192 Looks like @yaron2 confirmed that TTLs should "slide".

Yes, I think we should update the docs too

**Comment by DeepanshuA** [comment]
> * When a record is queried, a new WHERE clause is added to the query to make sure that records are returned only if "expire_at" is <= 0 OR "expire_at" < CURRENT_TIME (the time must use the database's clock, to avoid issues with clock skews). Records that have expired are thus silently ignored.

@ItalyPaleAle If I am understanding correctly, did you want to say "expire_at" is <= 0 OR "expire_at" >= CURRENT_TIME

**Comment by DeepanshuA** [comment]
> * Sliding TTL (the TTL period is reset upon modification of the row)

I like this idea of Sliding TTL and seems we are going ahead with it, cool!!

**Comment by ItalyPaleAle** [comment]
> If I am understanding correctly, did you want to say "expire_at" is <= 0 OR "expire_at" >= CURRENT_TIME 

Yes, you're correct. Let me fix the message :)
