### ISSUE TITLE
Mqtt PubSub multiplies messages when application unhealthy detected

### ISSUE THREAD

**Issue by bwojdyla** [dapr/components-contrib#2309]
## Expected Behavior

If dapr sidecar detects application is unhealthy it should unsubscribe from message broker without multiplying messages on queue.

## Actual Behavior

If dapr sidecar detects application is unhealthy it multiplies messages on consumer's queue.

## Steps to Reproduce the Problem
Enable app healthchecks https://docs.dapr.io/developing-applications/building-blocks/observability/app-health/
Configure 3 subscribtions for mqtt component (generally configure more than one subscribtion, The more subscripption the more copies of messages there would be)

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: testapp-pubsub
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
  - name: url
    value: "abc"
  - name: qos
    value: 2
  - name: retain
    value: "false"
  - name: cleanSession
    value: "false"
  - name: backOffMaxRetries
    value: "5"
```

Subscription 1
```
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: subscription1 
spec:
  pubsubname: testapp-pubsub
  topic: A
  route: /api/route1
```

Subscription 2
```
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: subscription2
spec:
  pubsubname: testapp-pubsub
  topic: B
  route: /api/route2
```

Subscription 3
```
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: subscription3
spec:
  pubsubname: testapp-pubsub
  topic: C
  route: /api/route2
```

In application prepare message handler so that it last some time ~5s. Later, while handler is running application must be killed.

1. Start dapr and application

```
time="2022-11-24T08:22:23.562665598Z" level=info msg="app is subscribed to the following topics: [C A B] through pubsub=testapp-pubsub" app_id=testapp instance=dc02d2b2cc3c scope=dapr.runtime type=log ver=1.9.4
time="2022-11-24T08:22:23.562701843Z" level=debug msg="subscribing to topic='A' on pubsub='testapp-pubsub'" app_id=testapp instance=dc02d2b2cc3c scope=dapr.runtime type=log ver=1.9.4
time="2022-11-24T08:22:23.562715411Z" level=info msg="initializing the subscriber" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:23.567539104Z" level=debug msg="subscribing to topic='B' on pubsub='testapp-pubsub'" app_id=testapp instance=dc02d2b2cc3c scope=dapr.runtime type=log ver=1.9.4
time="2022-11-24T08:22:23.567577608Z" level=info msg="re-initializing the subscriber" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:23.571991444Z" level=debug msg="subscribing to topic='C' on pubsub='testapp-pubsub'" app_id=testapp instance=dc02d2b2cc3c scope=dapr.runtime type=log ver=1.9.4
time="2022-11-24T08:22:23.572032501Z" level=info msg="re-initializing the subscriber" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:23.720681645Z" level=debug msg="App health probe successful: true" app_id=testapp instance=dc02d2b2cc3c scope=dapr.apphealth type=log ver=1.9.4

```
Notice that subscription order is A => B => C. Not sure if this is relevant.

3. Send single message for topic A
5. Kill application but leave dapr running

```
time="2022-11-24T08:22:44.975119851Z" level=debug msg="Probing app health" app_id=testapp instance=dc02d2b2cc3c scope=dapr.apphealth type=log ver=1.9.4
time="2022-11-24T08:22:45.226630459Z" level=debug msg="App health probe successful: true" app_id=testapp instance=dc02d2b2cc3c scope=dapr.apphealth type=log ver=1.9.4
time="2022-11-24T08:22:47.528271409Z" level=debug msg="Processing MQTT message A#3 (retained=false)" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:49.975533018Z" level=debug msg="Probing app health" app_id=testapp instance=dc02d2b2cc3c scope=dapr.apphealth type=log ver=1.9.4
time="2022-11-24T08:22:50.231616619Z" level=debug msg="App health probe successful: true" app_id=testapp instance=dc02d2b2cc3c scope=dapr.apphealth type=log ver=1.9.4
time="2022-11-24T08:22:50.827145674Z" level=error msg="Failed processing MQTT message A#3: error from app channel while sending pub/sub event to app: dial tcp4 127.0.0.1:5000: connect: connection refused" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:50.82719002Z" level=debug msg="Re-publishing message A#3" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:50.827198902Z" level=debug msg="mqtt publishing topic A" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:50.83366549Z" level=debug msg="Taking a retriable error token" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:50.833712745Z" level=debug msg="Resumed after pausing for 1.994µs" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:50.833730271Z" level=debug msg="Processing MQTT message A#4 (retained=false)" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:50.833944088Z" level=error msg="Failed processing MQTT message A#4: error from app channel while sending pub/sub event to app: dial tcp4 127.0.0.1:5000: connect: connection refused" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:50.833986479Z" level=debug msg="Re-publishing message A#4" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:50.833995973Z" level=debug msg="mqtt publishing topic A" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:50.839603203Z" level=debug msg="Taking a retriable error token" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:50.933851077Z" level=debug msg="Resumed after pausing for 94.185293ms" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:50.933942187Z" level=debug msg="Processing MQTT message A#5 (retained=false)" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4

```
From this point application fails to process message remove it from queue and re-publish it. It does it on and on until dapr detects application is unhealthy.

```
time="2022-11-24T08:22:54.97549954Z" level=debug msg="Probing app health" app_id=testapp instance=dc02d2b2cc3c scope=dapr.apphealth type=log ver=1.9.4
time="2022-11-24T08:22:54.975894951Z" level=debug msg="App health probe successful: false" app_id=testapp instance=dc02d2b2cc3c scope=dapr.apphealth type=log ver=1.9.4
time="2022-11-24T08:22:54.975969145Z" level=warning msg="App entered un-healthy status" app_id=testapp instance=dc02d2b2cc3c scope=dapr.apphealth type=log ver=1.9.4
time="2022-11-24T08:22:54.976013887Z" level=info msg="re-initializing the subscriber" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:54.984464698Z" level=debug msg="Processing MQTT message A#46 (retained=false)" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:54.984564742Z" level=error msg="Failed processing MQTT message A#46: error from app channel while sending pub/sub event to app: rpc error: code = Internal desc = app is not in a healthy state" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:54.984593566Z" level=debug msg="Re-publishing message A#46" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:54.984600879Z" level=debug msg="mqtt publishing topic A" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:54.98456658Z" level=info msg="re-initializing the subscriber" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:54.990251617Z" level=debug msg="Taking a retriable error token" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:54.993952619Z" level=debug msg="Processing MQTT message A#46 (retained=false)" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:54.994089737Z" level=error msg="Failed processing MQTT message A#46: error from app channel while sending pub/sub event to app: rpc error: code = Internal desc = app is not in a healthy state" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:54.99411731Z" level=debug msg="Re-publishing message A#46" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:54.994140085Z" level=debug msg="mqtt publishing topic A" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.001079626Z" level=debug msg="Taking a retriable error token" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.034259698Z" level=debug msg="Resumed after pausing for 65.826372ms" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.034343884Z" level=error msg="no handler defined for topic A" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.034355021Z" level=debug msg="Re-publishing message A#46" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.034363093Z" level=debug msg="mqtt publishing topic A" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.038740655Z" level=debug msg="Taking a retriable error token" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.134192709Z" level=debug msg="Resumed after pausing for 143.88785ms" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.234471758Z" level=debug msg="Resumed after pausing for 233.339054ms" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.234529498Z" level=error msg="no handler defined for topic A" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.234537763Z" level=debug msg="Re-publishing message A#47" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.234544058Z" level=debug msg="mqtt publishing topic A" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.239599279Z" level=debug msg="Taking a retriable error token" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.333802142Z" level=debug msg="Resumed after pausing for 294.99889ms" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:55.434010883Z" level=debug msg="Resumed after pausing for 194.362971ms" app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:57.462065434Z" level=debug msg="Refreshing all mDNS addresses." app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:57.462109067Z" level=debug msg="no mDNS apps to refresh." app_id=testapp instance=dc02d2b2cc3c scope=dapr.contrib type=log ver=1.9.4
time="2022-11-24T08:22:59.975223416Z" level=debug msg="Probing app health" app_id=testapp instance=dc02d2b2cc3c scope=dapr.apphealth type=log ver=1.9.4
time="2022-11-24T08:22:59.975498454Z" level=debug msg="App health probe successful: false" app_id=testapp instance=dc02d2b2cc3c scope=dapr.apphealth type=log ver=1.9.4

```

In logs above there are information about _re-initializing the subscriber_. And message is being multiplied on queue. In this case I had 5 copies on queue. But this number varies from run to run.
It looks like from point in time when unhealthy application is detected messages are no longer acknowledged but are re-publish to queue and are processed by multiple times (by multiple threads).

Full dapr sidecar logs:
[message_copies.log](https://github.com/dapr/components-contrib/files/10082911/message_copies.log)

It might be related to this https://github.com/dapr/components-contrib/issues/2306.

**Comment by shivamkm07** [comment]
I can reproduce the issue. Also, if there are multiple applications subscribing to the same topic, and one of the applications fail, the message gets re-delivered to **all** applications indefinitely, even for those applications which are healthy.

This issue is independent of #2306. It's happening because of https://github.com/dapr/components-contrib/blob/ead9ffa665dd15474ab04392309789c7754aaf8d/pubsub/mqtt/mqtt.go#L261, where if message handler fails (which will if app gets unhealthy), dapr re-publishes the message to broker and so message gets re-delivered to all applications. 
I see this being added in https://github.com/dapr/components-contrib/pull/1798, and here intentionally backoff retries were removed and re-publishing was added. Note that earlier, in backoff retries, we were just calling handler again in case of errors and so other applications were not affected at all, and also it wasn't retried indefinitely.(https://github.com/dapr/components-contrib/blob/9350f2ef580f339e2e1eb33be713e1ced3e12463/pubsub/mqtt/mqtt.go#L345). Also the issue doesn't come up with 1.8.6, again verifying the same. 

cc @ItalyPaleAle @DeepanshuA @pravinpushkar @akhilac1

**Comment by ItalyPaleAle** [comment]
@shivamkm07 good investigation.

#1798 removed built-in retries because those should be handled with Resiliency instead. This was made by design.

I do understand how re-publishing the message is creating this issue, however. And this seems to be quite the pickle, all due to the fact that MQTT doesn't have the concept of "NACK's" in the current version we support (seems that something was added in [MQTT5](https://www.hivemq.com/blog/mqtt5-essentials-part5-client-feedback-negative-ack/))

- If we remove the re-publish, messages that fail to be retried (using Resiliency) would be dropped if there's a failure. This may potentially violate the "at least once" delivery guarantee.  
  Worth pointing out that in Dapr 1.8, this is essentially what happens too, except that there's 3 built-in retries. If the app is down and Dapr fails to send the message to the app,  exhausting the built-in retries, the message is silently dropped.
- Keeping the re-publish seems to be causing this issue.

I suppose that given the circumstances, removing the re-publish may be the only option, as the downsides of re-publishing may be a worse issue. But we should be aware that doing that (and what happens in Dapr <= 1.8) could cause messages to be dropped.

**Comment by shivamkm07** [comment]
> If we remove the re-publish, messages that fail to be retried (using Resiliency) would be dropped if there's a failure. This may potentially violate the "at least once" delivery guarantee.

In case of failures, we don't ack the message back to broker both in [1.9](https://github.com/dapr/components-contrib/blob/ead9ffa665dd15474ab04392309789c7754aaf8d/pubsub/mqtt/mqtt.go#L272) and [1.8](https://github.com/dapr/components-contrib/blob/9350f2ef580f339e2e1eb33be713e1ced3e12463/pubsub/mqtt/mqtt.go#L349) (after all retries are exhausted). Since default value of QOS is 1, the broker will re-send the messages which are not acked, and would keep repeating till they are acked.. i.e. till the handler succeeds. So imo the messages shouldn't be lost even if we don't retry at all. Note here that in mqtt, *Not Acking a message* is similar in behavior to *NACK*, the difference is that messages are re-sent only after the retry interval of the broker. Some brokers like emqx allow configuring the field(https://www.emqx.io/docs/en/v2.0/config.html#mqtt-session-parameters) but not all.

>we should be aware that doing that (and what happens in Dapr <= 1.8) could cause messages to be dropped.

Also we already have the disconnection scenario in certification test (https://github.com/dapr/components-contrib/blob/v1.8.6/tests/certification/pubsub/mqtt/README.md#infra-test) and it seemed working fine for 1.8. Do we have any specific scenario in which mesages were being lost in Dapr <= 1.8?

**Comment by ItalyPaleAle** [comment]
Alright, sounds good! I forgot about the QOS.

**Comment by shivamkm07** [comment]
Can we revert back to backoff retries specifically for mqtt? I think that might be better optimized than just leaving it to broker to re-send the messages as retry-interval is not configurable for all brokers and waiting for that much time for the retries might not be preferred option. Also since it's the pubsub handler that failed, it would make more sense for Dapr sidecar to retry sending it to app a few times before waiting for broker.

Note that this would mean to bring back [backoffmaxretries](https://github.com/dapr/components-contrib/blob/ead9ffa665dd15474ab04392309789c7754aaf8d/pubsub/mqtt/metadata.go#L142) as it was deprecated in 1.9. Thoughts?

**Comment by shivamkm07** [comment]
> Can we revert back to backoff retries specifically for mqtt? I think that might be better optimized than just leaving it to broker to re-send the messages as retry-interval is not configurable for all brokers and waiting for that much time for the retries might not be preferred option. It might also break our existing certification tests again due to time issues. Also since it's the pubsub handler that failed, it would make more sense for Dapr sidecar to retry sending it to app a few times before waiting for broker.
> 
> Note that this would mean to bring back [backoffmaxretries](https://github.com/dapr/components-contrib/blob/ead9ffa665dd15474ab04392309789c7754aaf8d/pubsub/mqtt/metadata.go#L142) as it was deprecated in 1.9. Thoughts?

**Comment by ItalyPaleAle** [comment]
For retries within the same sidecar, one should use Resiliency. I don't think we should support that on a component-by-component basis, and we should actually remove built-in retries from all components (see #1797)

**Comment by DeepanshuA** [comment]
We don't need to support or bring back `backoffmaxretries`, we can simply keep using `maxRetriableErrorsPerSec`. But, instead of re-publishing, we can simply call back topic handler. So, essentially only that particular subscription is going to be affected and NOT all.

**Comment by ItalyPaleAle** [comment]
>  instead of re-publishing, we can simply call back topic handler. So, essentially only that particular subscription is going to be re-tried and NOT all.

Yes, that's what #1797 is about. People should use resiliency for this.

As for re-publishing, I agree removing that seems to be the right thing to do.
