### ISSUE TITLE
Usage of CloudEvents SDK GO

### ISSUE THREAD

**Issue by matzew** [dapr/components-contrib#2495]
## Describe the proposal

While looking at the code of the `contrib` repo, especially around the subject of "Cloud Events", I noticed on areas like here:
https://github.com/matzew/components-contrib/blob/master/pubsub/envelope.go#L105-L117

that the [Golang SDK for CloudEvents](https://github.com/cloudevents/sdk-go) is not used.

Would the community be interested in using that SDK?

**Comment by matzew** [comment]
@berndverst Do you have context here, why the SDK was not choosen? If interest in using that, I could take a look...

**Comment by berndverst** [comment]
I do not know @matzew -- the foundations of that code were before my time. I assume it has to do with maximizing compatibility. @yaron2 will know more here. Perhaps it's simply that folks didn't know there was a Go SDK at the time.

That being said, I highly doubt the existing behavior can be exactly retained without breaking changes by switching to the cloud events Go SDK.

Also keep in mind that we need to maintain the JSON / struct representation anyway because we must not change the behavior of our API output (HTTP JSON, and gRPC protos), so there may be little value in using the official cloud event SDK.

Unless there is a functionality / behavior reason for swapping this, I do not suggest making this swap.
There is more code here - https://github.com/dapr/dapr/blob/master/pkg/runtime/pubsub/cloudevents.go and all over `pkg/runtime` in `dapr/dapr`.

**Comment by berndverst** [comment]
One example:

For legacy reasons we must support both `traceid` and `traceparent` at this time (they have the same value). This of course wouldn't when using the Cloud Events 1.0.2 spec alone.
