### ISSUE TITLE
Dapr Sidecar loses connection to Azure Service Bus, both consuming and publishing messages fails

### ISSUE THREAD

**Issue by thoemmi** [dapr/components-contrib#2617]
## Expected Behavior

PubSub with Azure Service Bus should publish and consume infinitely.

## Actual Behavior

After a while (a couple of hours today) neither publishing nor consuming messages works.

Notable log lines are
```
Too many failed attempts while publishing Service Bus message (nil): *Error{Condition: amqp:not-allowed, Description: A link to connection '72854951' $cbs node has already been opened., Info: map[]}
```
and
```
Error reading from topic publiccloudconnectorgwinbox. *Error{Condition: amqp:not-allowed, Description: A link to connection '72854951' $cbs node has already been opened., Info: map[]}
```

Here's the full log of the Dapr sidecar since the last restart of the pod.

[publiccloudgateway-deployment-5376ce03-588df56647-g6p4h.log](https://github.com/dapr/components-contrib/files/10872482/publiccloudgateway-deployment-5376ce03-588df56647-g6p4h.log)

## Steps to Reproduce the Problem

Have a sidecar with Service Bus subscriptions and eventually the sidecar stops publishing and consuming the servicebus subscription.

We're using the AKS extension, which keeps Dapr up to date autometically, so we're on Dapr 1.10.2

**Comment by DeepanshuA** [comment]
Just trying to analyze the issue here.

Was this working before upgrade to Dapr 1.10.2 ?

This seems to have been reported and fixed here in Azure SDK: https://github.com/Azure/azure-sdk-for-go/issues/19347
It seems to have fixed with PRs like https://github.com/Azure/azure-sdk-for-go/pull/19326 and https://github.com/Azure/azure-sdk-for-go/pull/19492.

From all these, it seems that cbs connection is an exclusive link and we might need to close it, whenever-wherever required.

I am not sure, but just a theory/possibility:

While sending a message, it receives an error and goes in this loop:
https://github.com/dapr/components-contrib/blob/907b6b9ebeeba9c4f74f4df1ae3316eae3cb784e/internal/component/azure/servicebus/publisher.go#L62

Here, it does not go into NetworkError condition, as connection is already open.
It doesn't satisfy IsRetriableAmqpError as well, as `Condition: amqp:not-allowed` is not one of https://github.com/dapr/components-contrib/blob/907b6b9ebeeba9c4f74f4df1ae3316eae3cb784e/internal/component/azure/servicebus/errors.go#L11

Finally, it backoffs permanently and you keep receiving same error for all messages published.

1. Do we need to re-connect while backing off permanently, may be depending on some Conditions apart from NetworkError? So that further messages might be sent
2. As per `Condition: amqp:not-allowed`, is there any setting required by your side on ServiceBus to allow this? And, were same settings working earlier with Dapr 1.9.x?

**Comment by thoemmi** [comment]
I don't remember having seen this issue before 1.10.x. As far as I know we didn't change any settings recently, but we upgrade the Pulumi packages for our deployment.

**Comment by thoemmi** [comment]
We retain the AKS logs in Log Analytics for 30 days, so we've been able to do some research.
In fact, the error first occured 2/28 with Dapr version 1.10.0.

<details>
    <summary>Kusto query</summary>

```kusto
ContainerLog
| where TimeGenerated > ago(30d)
| where LogEntry has "node has already been opened"
| where LogEntry has "scope=dapr.contrib type=log"
| extend DaprVersion = substring(LogEntry,-6,6)
| project TimeGenerated,DaprVersion,LogEntry
| summarize count() by DaprVersion, length=bin(TimeGenerated, 1d)
```

<img width="371" alt="image" src="https://user-images.githubusercontent.com/73690/222693546-5c86507b-8bdd-4e1f-a0c1-38b0bacf6301.png">

</details>

**Comment by ItalyPaleAle** [comment]
Waiting for https://github.com/Azure/azure-sdk-for-go/pull/20334 to be released. We will include this in Dapr 1.10.3
