### ISSUE TITLE
[RocketMQ] compatibility：topic will change when namespaced has been configured

### ISSUE THREAD

**Issue by naah69** [dapr/components-contrib#2731]
when i upgrade dapr from 1.9.4 to 1.10.4,the topic changed.

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/25682169/229021480-53c0c34b-df28-4d1c-91a5-8bd040e933e1.png">

when i view the code,i find the reson:
https://github.com/dapr/dapr/blob/150b49c276c6b038364368e50427a20954953b0e/pkg/runtime/runtime.go#L793

why not add a switch to open it in config?

and this rule is so ugly, maybe we should add separator `.` between namespace and topic,just like `{namesapce} => test.notify`

**Comment by mukundansundar** [comment]
Hi @naah69 Based on the discussion that I had offline with @yaron2 , the change that you are pointing to 

> https://github.com/dapr/dapr/blob/150b49c276c6b038364368e50427a20954953b0e/pkg/runtime/runtime.go#L793

is intentional. This is considered a bug that was [fixed](https://github.com/dapr/dapr/issues/5472) as part of 1.10 to allow namespaced consumer groups as documented [here](https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-namespace/#with-namespace-consumer-groups).

cc @yaron2 @berndverst
