### ISSUE TITLE
Bindings - Event hubs - Support Storage ConnectionString - Emulator

### ISSUE THREAD

**Issue by perokvist** [dapr/components-contrib#279]
##  Support Storage ConnectionString
To be able to use the Azure Storage emulator, only using storageAccountName and storageAccountKey isn't enough, the host needs to be changed. It might be better to go with a connectionString (to enable - UseDevelopmentStorage=true).

https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#connect-to-the-emulator-account-using-the-well-known-account-name-and-key

**Comment by marxxxx** [comment]
This would be very helpful.

**Comment by oising** [comment]
@dapr-bot reopen

**Comment by oising** [comment]
And again...

**Comment by oising** [comment]
la-la-la-la-la.

**Comment by perokvist** [comment]
I think this "issue" might be even more relevant, now the Aspire+Dapr story.
Where the is a component for using the Cosmos Emulator. Showcasing more parameters added to the connectionstring

`AccountKey=xxx;AccountEndpoint=https://127.0.0.1:65236;DisableServerCertificateValidation=True;`

**Comment by oising** [comment]
@dapr-bot reopen

**Comment by oising** [comment]
Bump.

**Comment by berndverst** [comment]
This should already work for quite some time. https://docs.dapr.io/reference/components-reference/supported-bindings/eventhubs/
https://docs.dapr.io/reference/components-reference/supported-bindings/eventhubs/
https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/

There is a `storageConnectionString` metadata property for this since Dapr 1.10.

This is directly connected to the https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob#NewClientFromConnectionString SDK method.

You may need to configure HTTPS support in `azurite` however, because we have not exposed the option to set the TLS configuration of the underlying Storage Client. We do not plan to expose this.

Please ensure to configure a certificate when using Azurite. https://github.com/Azure/Azurite/blob/main/README.md#https-setup
