### ISSUE TITLE
CloudEvent(s)Envelope inconsistently named

### ISSUE THREAD

**Issue by LMWF** [dapr/components-contrib#284]
## What version of Dapr?

0.3

## Expected Behavior

The same structure in different languages/repos should have the same name (perhaps other than language casing conventions).  The envelope used for pub/sub is named `CloudEventEnvelope` in protobuf's, 
https://github.com/dapr/dapr/blob/2cdc91c3f41b97280fffed378bbc15c9fe074a64/pkg/proto/daprclient/daprclient.proto#L21

but is named `CloudEventsEnvelope` in components-contrib, 

https://github.com/dapr/components-contrib/blob/e7639f90c9d08a01319e530a6e5ecb578a69b7d2/pubsub/envelope.go#L23

which is referred to by the runtime.

**Comment by pkedy** [comment]
Because the Cloud Events spec has free form fields, it seems like `CloudEventsEnvelop` was removed in favor of `map[string]interface{}`. As indicated above, `CloudEventsEnvelop` is probably how the protobuf message should be named (since it is the CloudEvents spec), but renaming it is a breaking change. Since there was agreement to change the Go struct and now that Go struct is retired, I am closing this issue.
