### ISSUE TITLE
Zeebe command binding component as stable

### ISSUE THREAD

**Issue by alicejgibbons** [dapr/components-contrib#2941]
## Describe the feature
Zeebe command output binding component requires certification tests to be moved from Alpha to Beta to Stable.
https://docs.dapr.io/reference/components-reference/supported-bindings/zeebe-command/

## Release Note

RELEASE NOTE: ADD Zeebe command binding component as stable.

**Comment by cicoyle** [comment]
Current status = `Alpha`. Desire to move to `Beta`.

**Beta** requirements:
- [ ] The component must pass all the component conformance tests defined to satisfy the component specification
- [ ] The component conformance tests have been run in a Dapr maintainers managed environment
- [ ] The component contains a record of the conformance test result reviewed and approved by Dapr maintainers with specific components-contrib version
- [ ] Recommended for only non-business-critical uses because of potential for incompatible changes in subsequent releases

Once [this WIP PR to migrate Zeebe e2e tests to certification tests](https://github.com/dapr/components-contrib/pull/3112) is completed & merged, then the Beta requirements can be revisited and likely completed.

**Comment by berndverst** [comment]
Ideally this issue is assigned to @akkie because he did the main work to make this happen.
