### ISSUE TITLE
Zeebe jobworker binding component as stable

### ISSUE THREAD

**Issue by alicejgibbons** [dapr/components-contrib#2942]
## Describe the feature
Zeebe command input binding component requires certification tests to be moved from Alpha to Beta to Stable.
https://docs.dapr.io/reference/components-reference/supported-bindings/zeebe-jobworker/

## Release Note

RELEASE NOTE: ADD Zeebe jobworker binding component as stable.

**Comment by cicoyle** [comment]
Current status = `Alpha`. Desire to move to `Beta` then `Stable`.

**Beta** requirements:
- [ ] The component must pass all the component conformance tests defined to satisfy the component specification
- [ ] The component conformance tests have been run in a Dapr maintainers managed environment
- [ ] The component contains a record of the conformance test result reviewed and approved by Dapr maintainers with specific components-contrib version
- [ ] Recommended for only non-business-critical uses because of potential for incompatible changes in subsequent releases

**Stable** requirements:

- [ ] The component must have component [certification tests](https://docs.dapr.io/operations/components/certification-lifecycle/#certification-tests) validating functionality and resiliency
- [ ] The component is maintained by Dapr maintainers and supported by the community
- [ ] The component is well documented and tested
- [ ] The component has been available as Alpha or Beta for at least 1 minor version release of Dapr runtime prior
- [ ] A maintainer will address component security, core functionality and test issues according to the Dapr support policy and issue a patch release that includes the patched stable component

Once [this WIP PR to migrate Zeebe e2e tests to certification tests](https://github.com/dapr/components-contrib/pull/3112) is completed & merged, then the Stable requirements can likely be completed.

**Comment by berndverst** [comment]
Ideally this issue would be assigned to @akkie since he did the real work here.
