### ISSUE TITLE
[Configuration API] Unable to subscribe to Redis hash type

### ISSUE THREAD

**Issue by codding-y** [dapr/components-contrib#2969]
When using the configuration API of the .NET Dapr SDK, I encountered a situation where the Redis data type is hash type, the data has been changed, but the subscription has not been triggered. But when the data type is string, everything is normal. So I would like to ask if this is an issue in the Redis component itself?

For details, please refer to: https://github.com/dapr/dotnet-sdk/issues/1117

**Comment by codding-y** [comment]
@berndverst  Can you provide me with some help?

**Comment by shivamkm07** [comment]
@codding-y this is expected behaviour(at least per current implementation). Configuration API component currently only subscribes to keys with *string* data type (See here: https://github.com/dapr/components-contrib/blob/1ab15ef04ba571ff7c7c51b299d77afaa4565071/internal/component/redis/v8client.go#L77)

This is because currently the return type in Configuration component implementation is set to string now. To support other data types like Redis hash data types, the response interface needs to be changed. For more details, see here: https://github.com/dapr/components-contrib/issues/2408

cc @berndverst @ItalyPaleAle  thoughts on this?
