### ISSUE TITLE
Azure event hub pubsub component fails to subscribe to topic when using managed identity from container app

### ISSUE THREAD

**Issue by JasonRodman** [dapr/components-contrib#3097]
## Expected Behavior

I should be able to subscribe to a topic and receive events from azure event hub.

## Actual Behavior

No events are delivered, and the dapr sidecar reports an error that it cannot read from the state storage account with the following error.

```
Error from event processor: GET https://[storageaccount].blob.core.windows.net/[containername]
--------------------------------------------------------------------------------
RESPONSE 403: 403 This request is not authorized to perform this operation using this permission.
ERROR CODE: AuthorizationPermissionMismatch
--------------------------------------------------------------------------------
<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:96e866a8-401e-0017-5eec-d58360000000\nTime:2023-08-23T18:02:56.2005961Z</Message></Error>
--------------------------------------------------------------------------------
```

## Steps to Reproduce the Problem

1. Created blob storage account.
2. Created event hub namespace.
3. Created azure container app with system assigned managed identity.
4. Assigned "Azure Event Hubs Data Owner" role to the container app identity for the event hub namespace.
5. Assigned "Storage Account Contributor" role to the container app identity for the storage account.

Tried assigning progressively higher roles to the container app to see what would give it sufficient access to the storage account:

1. Storage account data owner
2. Contributor
3. Owner

Initially it could not create hubs for each topic until it had "storage account data owner" role assigned. Once hubs were created the current error above was reported and not even highest level of access helped. It's not clear from documentation what access is required for this to operate when using role-based access for either the event hub namespace or storage account.

**Comment by berndverst** [comment]
@JasonRodman avoid system assigned identities in ACA. Each container app has a different identity, and unless you scoped your Dapr component to a single app you will encounter errors.

In short however, the role you are looking for is `Storage Blob Data Owner` or `Storage Blob Data Contributor`

I recommend using **user-assigned** identities. Attach those identities to every app which should load your component. (Also update the component to specify the `azureClientId` property to refer to the user-assigned identity you created)

The user-assigned identity will need `Azure Event Hubs Data Owner` (and actually more permissions unless you set Entitymanagement to false in the component - it would otherwise try to create a new EventHub for every new topic it encounters -- so you need some role with the appropriate permissions) and `Storage Blob Data Owner`

**Comment by berndverst** [comment]
Closing this container apps specific issue. I assume the guidance on Azure AD roles and identities in Container Apps resolved this issue.
