### ISSUE TITLE
ADDING NEW BROKER TO PUB/SUB COMPONENTS

### ISSUE THREAD

**Issue by g41797** [dapr/components-contrib#3125]
Hi
I'd like to add **NEW BROKER** to pub/sub components
Do I need to initiate some review/discuss process before start of the development?

**Comment by berndverst** [comment]
@g41797 which broker do you want to add?

And as a general guidance, we can only accept additional brokers that do not increase the binary too much (currently we are allowing up to 7MB), and additionally, the component must not introduce additional goroutines when the component is unused. This sometimes happens when dependencies start goroutines during the init functions of packages. We cannot accept such dependencies.
We can only accept pure Go implementations - we do not allow C bindings / extensions (CGO).

When you create your component I also suggest immediately trying to make sure that it can pass our conformance tests -- this ensures the component follows the Dapr Pubsub component standards: https://github.com/dapr/components-contrib/tree/master/tests/conformance

If the above restrictions do not work for you, you can consider creating a **pluggable component** instead: https://docs.dapr.io/developing-applications/develop-components/pluggable-components/pluggable-components-overview/

Pluggable components are provided by you and are not part of Dapr directly. So there would not be a pull request for that.

**Comment by g41797** [comment]
@berndverst thanks for quick response

[Memphis broker](https://memphis.dev) is fork of [NATS](https://nats.io)
[Memphis go client](https://github.com/memphisdev/memphis.go) is based on [NATS go client](https://github.com/nats-io/nats.go) - already part of Dapr:
```go
	github.com/nats-io/nats-server/v2 v2.9.21
	github.com/nats-io/nats.go v1.28.0
	github.com/nats-io/nkeys v0.4.4
```
Do you need additional information?
