### ISSUE TITLE
Add Available GitHub Slash Commands To Contributing.md 

### ISSUE THREAD

**Issue by cicoyle** [dapr/components-contrib#3137]
It would be nice if users knew more easily what [Github Slash Commands](https://techcommunity.microsoft.com/t5/educator-developer-blog/github-slash-commands-streamlining-your-workflow-as-a-student/ba-p/3824768) they are able to run in each repo. I would like to see a section added to the [CONTRIBUTING.md](https://github.com/dapr/components-contrib/blob/master/CONTRIBUTING.md) listing out what a user may run. [The file to view what commands a user may run is here.
](https://github.com/dapr/components-contrib/blob/master/.github/scripts/dapr_bot.js)

**Comment by berndverst** [comment]
General commands like `/assign` should probably be documented in `dapr/community`, other commands only apply to a subset of users which the maintainers deem trustworthy after becoming members of the Dapr Github org, and making a few repo specific contributions. I do not think it is necessary to document them at `CONTRIBUTING.md` because these commands can only be used by fewer than 20 people. This will confuse every one else.

We could create a new markdown document for approvers and maintainers that document these commands - but it is a bit weird in `CONTRIBUTING.md`.

See here: https://github.com/dapr/components-contrib/blob/master/.github/scripts/dapr_bot.js#L80

**Comment by shubham1172** [comment]
Hi @cicoyle I added this earlier https://docs.dapr.io/contributing/daprbot/, we can enhance the same doc if something is outdated. 

<img width="1111" alt="image" src="https://github.com/dapr/components-contrib/assets/22132944/06d9f3dd-fcb3-4ebc-a985-4b8ba0b25013">

**Comment by cicoyle** [comment]
Hey @shubham1172, I didn't realize that page existed. Thank you!

I believe it will be of value to our users to have that docs page linked inside the `contributing.md` file, as we don't want to duplicate the docs, but I believe explicitly adding a note to the `contributing.md` file be be helpful to existing and new users that want to contribute.
