### ISSUE TITLE
How to add custom middleware components with new capabilities

### ISSUE THREAD

**Issue by ParrySMS** [dapr/components-contrib#3196]
We hava some middleware components supported by Dapr. But how can I add custom middleware components for some private business logic.

According to the "How to: Author middleware components", it seems that we can have a custom custom HTTP middleware. But I can not find the way to register it. 

[https://docs.dapr.io/developing-applications/develop-components/develop-middleware/](https://docs.dapr.io/developing-applications/develop-components/develop-middleware/)

For example, I want to a custom impl like "type: middleware.http.somelowercase", how can I register it by this name "middleware.http.somelowercase" ?

According to the doc "How to: Implement pluggable components", 

[https://docs.dapr.io/developing-applications/develop-components/pluggable-components/develop-pluggable/](https://docs.dapr.io/developing-applications/develop-components/pluggable-components/develop-pluggable/)

the following component APIs are supported:

State stores
Pub/sub
Bindings
Secret stores

Our team already used some custom pluggable bindings components and we like the Dapr. Do we have the plan to add the "pluggable middleware components" in the Go SDKs to let people add the custom middleware components ?

**Comment by ParrySMS** [comment]
@artursouza @skyao @shubham1172 @akhilac1 @yaron2 @tanvigour @DeepanshuA @berndverst

**Comment by ItalyPaleAle** [comment]
We do not support pluggable components for middlewares.

If you do want to create your own middleware, you have 2 options:

1. Write it in Go and compile it as part of Dapr. This indeed requires building your own Dapr. You will register the component in Dapr by dropping a file in https://github.com/dapr/dapr/tree/master/cmd/daprd/components
2. Since Dapr 1.11, we also support WebAssembly (WASM) to create middlewares, which could be an alternative approach that doesn't require building your own Dapr.

Out of curiosity, what is the middleware for? I am wondering if maybe there are alternatives we could consider.
