### ISSUE TITLE
Azure service bus pubsub with system managed identity from Azure Container App not authenticating

### ISSUE THREAD

**Issue by Steve887** [dapr/components-contrib#3258]
## Expected Behavior

Queue messages read from Azure Service Bus

## Actual Behavior

Messages are dead lettered, and the following error appears in the console logs:

`App handler returned an error for message on queue tasks: retriable error occurred: retriable error returned from app while processing pub/sub event, body: {\"Message\":\"Login failed for user \\u0027\\u003Ctoken-identified principal\\u003E\\u0027.\`

## Steps to Reproduce the Problem

Created an Azure Container App, with `pubsub.azure.servicebus.queues` added to the container app environment.
Gave the component the metadata:
* namespaceName - full name of the service bus
* azureTenantId - tenant id being used

Gave the container app Azure Service Bus Data Owner, Receiver and Sender roles to the service bus (probably overkill, but unclear exactly what permission is needed).
Added a message to the queue.

Most documentation deals with user managed identity and assigned a client id to the component. I wish to use system managed identity as that is what we use for all our other services which is working fine for everything else.

**Comment by berndverst** [comment]
In Azure Container Apps there are two options:
system-managed identity or user-assigned identity.

Each Container Apps has a different system assigned identity. That means one Dapr component that is loaded by two container apps is loaded under two different identities. Each of these container app identities needs to be manually granted the appropriate data plane role from Service Bus.

It is a bad idea to use system managed identity because you would have to assign the roles each time you create a new container app.

It is our guidance (from the Dapr team) to only use user assigned identities for this reason. Every app in which you wish to use a given component should also receive the respective user assigned identity. Additionally, for user assigned identities you need to edit your component definition to specify the identity ID via the `azureClientId` metadata property.

This role assignment is likely to broad for your liking, but one role that will work for sure is `Azure Service Bus Data Owner`. You must grant either the user assigned identity (which you then attach everywhere) or each single app's own system assigned identity (tedious and error prone!) this role on the correct Service Bus scope.

I suspect due to your wish to use system assigned identities you didn't perform the assignment against each single container app, which likely is causing the issue here.

You should be able to omit the `azureTenantId` metadata property by the way.

**Comment by berndverst** [comment]
Note that you can still use system managed identities or even other user assigned identities for other purposes. But you'd simply attach the user assigned identity specifically for use with only the Dapr component. (But once again I need to point out you must list the `azureClientId` metadata in the component definition if you do use user assigned identity).

We have an extensive test suite that verified that managed identity is working for all Azure components. So I am confident you are encountering a configuration issue here.
