### ISSUE TITLE
Add support for fetching Azure App Config values by filter

### ISSUE THREAD

**Issue by tlund101** [dapr/components-contrib#3348]
## Describe the feature
Azure App Configurations supports getting a paginated list of configs if you pass in a key or label filter.  Support for this was added in the Go SDK back in September (https://github.com/Azure/azure-sdk-for-go/issues/15188#issuecomment-1712042399) It would be great to have this functionality included in Dapr as well.

## Release Note

RELEASE NOTE:
Add support for getting Azure App Config values using filters instead of specific key or label values

**Comment by berndverst** [comment]
More information needed.

- Why is this helpful or necessary?
- What would a complete request and a complete response look like for example?
- Does this change existing behavior?

My first thoughts as a maintainer are this:
We should support such a feature if we can directly add support for all current and future configuration stores as a native feature of the building block.

I want to avoid a world where components cannot be swapped out because they rely on request metadata to control component specific behavior.

What we did here https://docs.dapr.io/reference/components-reference/supported-configuration-stores/azure-appconfig-configuration-store/#azure-app-configuration-request-metadata was not a great design choice because it is component specific through the unstructured / untyped request metadata.

**Comment by tlund101** [comment]
>     * Why is this helpful or necessary?

It would allow fetching configuration keys using wildcard values.  Most useful when dealing with multi-tenant setups: https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/service/app-configuration#key-prefixes 

>  What would a complete request and a complete response look like for example?

Say you have two tenants, Tenant1 and Tenant2, and you have two configurations stored for each of them, URLKey and DBKey.  Right now, you have to do two separate requests if you want to get all configurations for one tenant.  With this change, you can do one request instead:  `http://localhost:3500/v1.0/configuration/azureappconfig?key=tenant1.*` and get back `{ tenant1.URLKey: tenant1URLValue, tenant1.DBKey: tenant1DBValue }`

> Does this change existing behavior?

No, this would be a logic change based on the value of the key.

Regarding other maintainability concerns, this endpoint can currently return multiple configurations by passing in no keys (and returning all configurations) and this change would not add any other metadata.  Platforms that don't support these filters would simply fail to find the key specified.
