### ISSUE TITLE
Redis State Store - Garnet support

### ISSUE THREAD

**Issue by pellerhorst** [dapr/components-contrib#3417]
## Describe the proposal
[Garnet](https://microsoft.github.io/garnet/docs) is a new cache-store that uses Redis' RESP protocol, so it is compatible with many Redis clients out of the box. Garnet is not a direct copy of Redis though, so some functionality (such as Lua script) is not implemented.

When setting a state, Dapr's Redis state store component checks if the Redis client supports json requests (by sending a JSON.GET request and seeing if an error is returned), and defines Lua scripts that perform multiple steps in the process of setting or deleting a state based on whether json requests are supported or not. Since Garnet does not support Lua scripts, it fails to save the state in either case and returns an 'Unknown Command' error. 

The Redis state store component would work with Garnet if the commands were sent over outside of Lua scripts.

The dotnet team had a similar issue with their IDistributedCache implementation of Redis, and they solved it in their most recent preview by [removing their Lua scripting entirely](https://github.com/dotnet/aspnetcore/issues/54685).

**Comment by berndverst** [comment]
If you can find a way to maintain existing Dapr component behavior (we have lots of tests) while removing Lua script then I would consider merging a pull request for this.

Dapr's implementation of State Store transactions currently heavily depends on these Lua script calls.

I suggest trying to modify the code here:
https://github.com/dapr/components-contrib/blob/93cf5cb2c96e91940d7d8c2da4376a09062df0b8/state/redis/redis.go#L61

And then running our state store conformance test against a local Redis Docker container to ensure that existing behavior is retained:

`go test -v -tags=conftests -count=1 ./tests/conformance -run="TestStateConformance/redis.v6"`
`go test -v -tags=conftests -count=1 ./tests/conformance -run="TestStateConformance/redis.v7"`

It would be strongly preferred if the existing Dapr components could simply be used with Garnet, rather than contributing another component which is essentially duplicate code with small alterations.

Please note:
Dapr State Store components must pass the above conformance test, unless you specifically do not wish to support Dapr's transaction interface. Without transactions Garnet wouldn't be able to be used Actor State Store (though because Redis isn't truly transactional this isn't really recommended anyway).

@pellerhorst you should be able to use the Dapr Redis Binding with Garnet today. Unless I'm mistaken it's mostly the state store component that is not compatible.
