### ISSUE TITLE
Add Etcd as a supported state

### ISSUE THREAD

**Issue by robertojrojas** [dapr/components-contrib#41]
## Describe the proposal
[Etcd](https://etcd.io/) is a distributed key-value store with features comparable to Redis. 
I propose adding Etcd as another state option for Dapr.

**Comment by youngbupark** [comment]
@robertojrojas 

The conversation gets longer. We encourage you to use GH issue when the conversation is longer. 

---
Build debuggable binary. later you can use dlv to debug daprd
```
make DEBUG=1 build
```

Then you can find the binaries in ./dist/{os}_{arch}/debug/ e.g. for macos, ./dist/darwin_amd64/debug

```
cd  ./dist/darwin_amd64/debug
mkdir components
```
create etcd yaml file in components directory. for example,
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.etcd
  metadata:
  - name: endpoints
    value: [etcd endpoint]
  - name: dialTimeout
    value: [dialTimeout]
  - name: operationTimeout
    value: [operationTimeout]
```
Now you’re ready to run daprd
```
$ daprd --help
# you can see the daprd options 

# make sure that placement is running as docker. 
# if you want to run placement service in  ./dist/darwin_amd64/debug, you need to remove placement container in docker first by running `docker rm --force dapr_placement`

$ daprd --dapr-id etcdtest  --placement-address localhost:50005
INFO[0000] starting Dapr Runtime -- version 0.1.0 -- commit 4358565-dirty 
INFO[0000] log level set to: info                       
INFO[0000] standalone mode configured                   
INFO[0000] dapr id: etcdtest                            
WARN[0000] failed to init input bindings: app channel not initialized 
WARN[0000] failed to init actors: actors: state store must be present to initialize the actor runtime 
INFO[0000] http server is running on port 3500          
INFO[0000] gRPC server is running on port 50001         
INFO[0000] local service entry announced                
INFO[0000] dapr initialized. Status: Running. Init Elapsed 1.412489ms
```
Now daprd listen 3500 port for http. you can test your etcd implementation via this http endpoint.

Please see [state api spec](https://github.com/dapr/docs/blob/master/reference/api/state.md) to save and get the state into your etcd

If you want to debug daprd, you can attach dlv to daprd process because you build the binary with DEBUG=1 option.

**Comment by robertojrojas** [comment]
@youngbupark thanks, these instructions are really helpful!
