### ISSUE TITLE
Azure KeyVault secretstore BulkGet also retrieve deleted secrets

### ISSUE THREAD

**Issue by tcnghia** [dapr/components-contrib#656]
## Expected Behavior

Azure KeyVault secretstore BulkGet does not list deleted secrets.

## Actual Behavior

Deleted secrets are not excluded.

## Steps to Reproduce the Problem

Use Azure KeyVault secret store BulkSet 
## Release Note

RELEASE NOTE: **FIX** Exclude delete secrets in AzureKeyVault secret store BulkGet.

**Comment by tcnghia** [comment]
cc @cmendible @yaron2

**Comment by cmendible** [comment]
Hmmm that's weird. 

Since there's no deleted attribute in the response: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v51.1.0+incompatible/services/keyvault/2016-10-01/keyvault#SecretAttributes we can check for `secretResp.Attributes.Enabled == true`, but not sure it will work as a fix.

Also cause there is a `GetDeletedSecrets` (https://docs.microsoft.com/en-us/rest/api/keyvault/getdeletedsecrets) in the API I would expect `GetSecrets` (https://docs.microsoft.com/en-us/rest/api/keyvault/getsecrets) to return only available secrets.

**Comment by cmendible** [comment]
I just tested the GetSecrets API with a key vault containing an enabled and a deleted secret and the API did not return the deleted secrets.

But I did find that if at least one secret is disabled  then the Bulk Secret API fails.

I'll submit a PR to fix this behavior.
