### ISSUE TITLE
VaulttokenMountpath Issue

### ISSUE THREAD

**Issue by kamesh1677** [dapr/components-contrib#742]
## Expected Behavior

Vaulttokenmount path is not taking the vm location giving permission denied error.

## Actual Behavior

I created vaulttoken file inside root/tmp or etc or var folders and stored the vault token and trying to access the token from component yaml file.

I am facing the permission denied  problem for the path even though i applied  chmod 777 ,chown  still same problem.

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: vault-4fjh8:8270 # Optional. Default: "https://127.0.0.1:8200"
  - name: skipVerify # Optional. Default: false
    value : true
  - name: vaultTokenMountPath # Required. Path to token file.
    value : root/tmp/

 

couldn't read vault token: anypath (root/tmp/): permission denied  Please help on us.

RELEASE NOTE:

**Comment by kamesh1677** [comment]
Hi Team,

Any update on this issue.

**Comment by kamesh1677** [comment]
How to provide path to vaulttokenmount path.

Lets say vault token value I copied to one file and refereeing the path of the file in Vaulttokenmountpath .is it the right way to do it.

**Comment by kamesh1677** [comment]
Hi Team,

Any example to take the reference on the Vault secret store.

**Comment by DarqueWarrior** [comment]
I responded on SOF as well. The path should be to the complete file, not just the folder. What was the name of the file that you placed your token in? That filename should be included in the vaultTokenMountPath `root/tmp/filename`.  I personally think we should update the component to read the token from a secret instead of a file #794. The file also complicates deployment in K8s.
