### ISSUE TITLE
Update MySQL components to not only use files

### ISSUE THREAD

**Issue by DarqueWarrior** [dapr/components-contrib#802]
The MySQL binding and state store will suffer from the same issue of the Hashicorp Vault Secret store. Files can't be loaded into the sidecar so options need to be provided to read the required data from a secret instead of disk.

I propose we add the ability to leverage secrets and leave the file based access for local development.

**Comment by CodeMonkeyLeet** [comment]
Still in flight

**Comment by CodeMonkeyLeet** [comment]
This is still a long-term gap in the mysql component that prevents it from using secrets in a Kubernetes deployment.

**Comment by berndverst** [comment]
This issue is very vague. I'm closing this.

Please open a new issue if necessary, if so what I want to know is:
Which settings / options cannot be set via metadata right now but should be able to be set?

By the way you absolutely can mount files into the sidecar via the `volume-mount` annotations for the sidecar.
