### ISSUE TITLE
Add transactions support to Cassandra

### ISSUE THREAD

**Issue by yaron2** [dapr/components-contrib#86]
## Describe the proposal

Implement the Transactions interface for Cassandra.
That would make Cassandra be able to operate multi-operation transactions and be certified for an Actor state store for Dapr.

**Comment by berndverst** [comment]
Cassandra can only offer transactions when restricted to a single partition.

Since Dapr does not limit data to be stored in a single partition there is no way to guarantee transaction behavior.

I suggested **not proceeding with implementing transaction support**. Cassandra cannot be used as actor state store.

Thoughts @yaron2 @artursouza?
(As an aside, we also haven't received any requests from people wanting to use Cassandra as actor state store)
