### ISSUE TITLE
Why is the value of ConsumerID assigned to consumerGroup?

### ISSUE THREAD

**Issue by iamazy** [dapr/components-contrib#928]
Hi, there

https://github.com/dapr/components-contrib/blob/464d53d94b259bd0ac2fc6342816c4dea5f3210f/pubsub/kafka/kafka.go#L50
https://github.com/dapr/components-contrib/blob/464d53d94b259bd0ac2fc6342816c4dea5f3210f/pubsub/kafka/kafka.go#L126

Why is the value of `kafkaMetadata`'s `ConsumerID` assigned to `Kafka`'s `consumerGroup`, I think they are not the same thing! It's better to change it to consumerGroup, i.e.

```diff
type kafkaMetadata struct {
	Brokers         []string `json:"brokers"`
--	ConsumerID      string   `json:"consumerID"`
++      ConsumerGroup   string   `json:"consumerGroup"`
	AuthRequired    bool     `json:"authRequired"`
	SaslUsername    string   `json:"saslUsername"`
	SaslPassword    string   `json:"saslPassword"`
	MaxMessageBytes int      `json:"maxMessageBytes"`
}
```

**Comment by iamazy** [comment]
@khous

**Comment by CodeMonkeyLeet** [comment]
@pkedy This seems confusing alright, though it's API breaking to change the name. Given that the Kafka pubsub component is in Beta, we should fix this sooner rather than later. 

On a related note, the field is not described in Dapr docs today, though it's _de facto_ a part of the public metadata. Given that the Kafka binding does [document the equivalent field](https://docs.dapr.io/reference/components-reference/supported-bindings/kafka/) as `consumerGroup`, we should probably standardize that.

**Comment by pkedy** [comment]
@iamazy @CodeMonkeyLeet If I understand the history correctly, `consumerID` is used consistently across the other pubsub components in order to try make the concept generic. If more of the components are currently using `consumerID` (which I think they are), we probably want to standardize on that. Basically favoring consistency in the settings over the component level details (which is sort of what Dapr is all about).

Also another docs issue... `consumerID` is not included in the Kafka pubsub docs page
https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/
The docs should mention that `consumerID` maps to Kafka's `consumerGroup`.

**Comment by iamazy** [comment]
> @iamazy @CodeMonkeyLeet If I understand the history correctly, `consumerID` is used consistently across the other pubsub components in order to try make the concept generic. If more of the components are currently using `consumerID` (which I think they are), we probably want to standardize on that. Basically favoring consistency in the settings over the component level details (which is sort of what Dapr is all about).
> 
> Also another docs issue... `consumerID` is not included in the Kafka pubsub docs page
> https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/
> The docs should mention that `consumerID` maps to Kafka's `consumerGroup`.

But I find that the other pubsub components‘s metadata fields are almost completely different with kafka.

**Comment by pkedy** [comment]
> But I find that the other pubsub components‘s metadata fields are almost completely different with kafka.

Of course fields between components are very different when there is no overlap. I am assuming the goal is/was that overlapping settings that control the same thing across components would have the same name. Since Dapr has so many contributors, that may not have been followed consistently. At least for usage of `consumerID` I found these components that use it.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/714039/122308538-943ab580-ceda-11eb-952a-e44ada0d7da6.png">

I think your point might be "why try to have a small handful of fields be consistent when the majority are component specific."

There are pros and cons to both approaches. Honestly, I'm indifferent here so it might be worth having a few more people weigh in. I've wondered about alias names which could help and also prevent breaking backward compatibility when we needy to change setting names. Either way, we need to pick out approach and make sure its followed consistently.

/cc @artursouza @yaron2

**Comment by CodeMonkeyLeet** [comment]
Adding a couple of thoughts to this:

> Also another docs issue... `consumerID` is not included in the Kafka pubsub docs page https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/
The docs should mention that `consumerID` maps to Kafka's `consumerGroup`.

The docs problem is probably contributing to the confusion here; not only is `consumerID` not documented for Kafka's pubsub, it's poorly documented for the other components [found in code](https://github.com/dapr/components-contrib/issues/928#issuecomment-862809254). Only Redis Streams pubsub lists it in the metadata spec, and MQTT only mentions it in a use case without prior context.

I agree that there can be value in cross-component naming consistency for metadata, but that probably needs to be highlighted more than it is today, and certainly needs to be called out as an expectation for contributors and reviewers to components-contrib for those properties. 

There's also still the side issue that Kafka's binding and pubsub components should use the same name for the property, so either one of them needs a change. For reference, MQTT uses `consumerID` uniformly between the bindings and pubsub components.

**Comment by artursouza** [comment]
> Adding a couple of thoughts to this:
> 
> > Also another docs issue... `consumerID` is not included in the Kafka pubsub docs page https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/
> > The docs should mention that `consumerID` maps to Kafka's `consumerGroup`.
> 
> The docs problem is probably contributing to the confusion here; not only is `consumerID` not documented for Kafka's pubsub, it's poorly documented for the other components [found in code](https://github.com/dapr/components-contrib/issues/928#issuecomment-862809254). Only Redis Streams pubsub lists it in the metadata spec, and MQTT only mentions it in a use case without prior context.
> 
> I agree that there can be value in cross-component naming consistency for metadata, but that probably needs to be highlighted more than it is today, and certainly needs to be called out as an expectation for contributors and reviewers to components-contrib for those properties.
> 
> There's also still the side issue that Kafka's binding and pubsub components should use the same name for the property, so either one of them needs a change. For reference, MQTT uses `consumerID` uniformly between the bindings and pubsub components.

I don't think we should optimize for metadata to be named the same in components - we don't expect those to be portable anyway. The cost of higher friction on understanding the parameters by name is not worth the arbitrary consistency here.

Because Kafka is not considered GA (yet) we could theoretically make a breaking change here - but I think it is a better customer experience to deprecate `consumerID` (emit a warning if it is used) and give preference to `consumerGroup`.

My 2 cents.
