### ISSUE TITLE
Certify Azure SQL Server as GA in state store

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#949]
## Describe the feature
Certify Azure SQL Server as GA in state store

## Release Note

RELEASE NOTE:

**Comment by daixiang0** [comment]
I would like to know what is the standard for GA, also I see #913, is it an enhancement?

**Comment by daixiang0** [comment]
Hi, @artursouza I would like to know what is the standard for GA, also I see #913, is it an enhancement?

**Comment by CodeMonkeyLeet** [comment]
@daixiang0 https://docs.dapr.io/operations/components/certification-lifecycle/ describes the stated standards for GA, and minimally it looks like a conformance test would need to be added for the sqlserver state component ... If you're interested, I'm actually looking into making the conformance tests for Azure services easier to set up. 

I've also looked into #913, and in discussion with @paulyuk, it's an enhancement and not a prerequisite for Azure SQL GA certification.

**Comment by daixiang0** [comment]
Is there a doc to comment maintainers for GA components?

**Comment by artursouza** [comment]
@daixiang0 I don't think we have an official list of maintainer per GA component. @msfussell thoughts on this?

**Comment by daixiang0** [comment]
As https://docs.dapr.io/operations/components/certification-lifecycle describes, we need a list for it, or we may comment it.

**Comment by artursouza** [comment]
@msfussell @CodeMonkeyLeet I think we need to have a special file on each component folder to mention who are the maintainers for each component and when there is a PR that affects the file, Dapr Bot automatically adds them to the review. In addition, the same list must be documented in the docs website for each component.

**Comment by CodeMonkeyLeet** [comment]
I agree that starting to track in specific component maintainers in the repo is going to be necessary for the GA certifications, and the suggestion aligns with how [Prow](https://github.com/kubernetes/test-infra/tree/master/prow) handles it. 

One thing to note is that you can already do this with the GitHub [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners#codeowners-syntax) file without having to add a bot for this. Since the component maintainers should have PR approval privileges, making them the subfolder owners in CODEOWNERS not only automatically adds them to component reviews, but also gives them codeowner approval rights. If we want to add additional pre-merge checks, then those are easier to incrementally add as Dapr Bot commands.

**Comment by berndverst** [comment]
## Component test plan

- [ ] [Integration] Test default vs custom SQLServer `schema` name handling
- [ ] [Integration] Test indexed properties actually indexed / not indexed. Error cases?
- [ ] [Integration] Test keyType / keyLength combination and allowed value range
- [ ] [Nice to have] remove duplicate tests across integration and conformance tests
- [ ] [Integration] Component must retry / reconnect when server or network errors are encountered
