### ISSUE TITLE
Rewrite Azure Event Hubs Pubsub component

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#951]
## Describe the feature
Rewrite Azure Events Hub by mapping pubsub component to Azure EventHub namespaces and Azure EventHub to a topic. Automatic provisioning of an EventHub (topic) can be enabled via metadata, similar to how is done for the Azure Service Bus component.
Certify Azure Events Hub as GA in pubsub.

## Release Note

RELEASE NOTE:  **Redesigned** Azure EventHub PubSub component

**Comment by yaron2** [comment]
This component needs to be removed completely, it cannot handle topics the way Dapr promises to consumers.

**Comment by artursouza** [comment]
@yaron2 @berndverst Can there be a new implementation of this component that handles that?

**Comment by berndverst** [comment]
@artursouza new implementation is different from GA -- as such it probably should start out as being Alpha or Beta?

I successfully ran the existing Azure Event Hubs Pub Sub conformance tests. If this doesn't meet our PubSub guarantees we need to overhaul our conformance tests too.

**Comment by berndverst** [comment]
Both @CodeMonkeyLeet  and I put significant work into investigating how to address the behavior of Event Hubs and how to GA this component. Unfortunately it just isn't impossible the way Event Hubs are designed and given the paradigm Dapr promises. Any workaround that could be implemented would be so complex (for example requiring lots of additional infra resources) such that we cannot GA the component.

We need to deprecate EventHubs for Release 1.4.

For reference I'm adding one PR that highlights several of the issues:
https://github.com/dapr/components-contrib/pull/1055

**Comment by berndverst** [comment]
@artursouza please update the issue title to the following text:

**Deprecate Azure Event Hubs Pubsub component.**

We should keep this as part of the 1.4 milestone as this requires docs changes.

**Comment by yaron2** [comment]
Again, I agree with the assessment @berndverst laid out. The namespace/topics design in Event Hubs makes this impossible.

**Comment by berndverst** [comment]
We will announce the deprecation in the docs as soon as possible and then beginning in the 1.4 release notes. The component will be removed from 1.6

https://github.com/dapr/components-contrib/issues/1073

**Comment by TalalMahmoodChaudhry** [comment]
Hi @yaron2 one question to this:

You state here that recommended use for dapr and Event Hub is binding componenet:
https://discord.com/channels/778680217417809931/778680217417809934/874326568825126932

However bindings do not support tracing IDs. Will this be supported for Event Hub binding in the future?
https://discord.com/channels/778680217417809931/781589820128493598/869281938567991356

**Comment by artursouza** [comment]
Updated issue (again) to describe the new goal of rewriting the Azure EventHub component with an abstraction that better matches the Dapr API for pubsub, respecting the pubsub name and pubsub topic concepts.

**Comment by mukundansundar** [comment]
I will be creating a certification issue and adding the Test Plan for the same shortly.

**Comment by mukundansundar** [comment]
## Current Behaviour 
- Authentication mechanism: connection string to the given event hub. (Can only connect to single event hub)
- Publish : Can only publish to the connected event hub. Does not support partition key.
- Subscription: Currently can only support a single subscriber connecting to a particular event hub using a single storage container. 
- Entity Management: Does not support on the fly creation of event hubs (topics) similar to how it is done in Azure Service Bus. 


In this scenario I will be using topic and event hub interchangeably. 

## Rewrite Goals
- Support AAD based authentication mechanism and if possible maintain backwards compatibility
- Publish: Honour the req.Topic field in incoming requests and use that to publish to request (topic) event hub. Support setting partition key when given in the request metadata. 
- Subscribe
  - Support having multiple subscribers to the same event hub (topic)
  - Honour the req.Topic field in the incoming SubscribeRequest and support subscribing to multiple event hubs.
- Entity Management
  - Support creation of event hubs (topics) on the fly if it does not exist and publish to and subscribe from a newly created event hub successfully 

## Proposed Design
Dapr Pubsub API allows users of Dapr to publish to publish to and subscribe from multiple topics in a given pubsub. 
Event hub namespace is a management container for multiple [event hubs (topics)](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features#namespace). 

### Authentication

Each event hub is going to be considered as a topic in Dapr parlance and the connection and authentication needs to be at least at the event hub namespace level, to be able to connect to multiple event hubs. 

Apart from the connection string being available as an authentication mechanism, Azure also support client certificate, client credentials, MSI based AAD authentication mechanisms for event hubs. There is a common library in place for [Azure components](https://github.com/dapr/components-contrib/tree/master/authentication/azure) and that can be used. 

If backwards compatibility needs to be maintained, connecting directly to event hub using event hub connection string instead of the event hub namespace level connection string, then the req.Topic field in PublishRequest/SubscribeRequest will be ignored and the component will be able to connect to only the configured event hub. 


- **TODO** Accept both event hub connection string and event hub namespace level connection string and do all necessary validations for the same
- **TODO** Add another JWT based TokenProvider for AMQP protocol based connection. 

### Publish

Based on connection string or AAD authentication, use the req.Topic field correctly to connect to a given event hub. Support setting partition key field in the message based on the field being set in the incoming request metadata.

- **TODO** Support setting `partitionKey` based on metadata field
- **TODO** Support publishing to multiple topics based on the incoming req.Topic field and the specified authentication mechanisms (see above)

### Subscribe

Continue to use [EventProcessorHost](https://github.com/Azure/azure-event-hubs-go#event-processor-host) based client to support partitioned consumer pattern based communication and also to avoid explicit management of partition and checkpoint. 

Based on connection string or AAD authentication, use the req.Topic field correctly to connect to a given event hub. 

Currently given a storage account and a storage container, only one subscriber can be used at a given time since the checkpoint blobs are created as partition IDs directly (eg: 0,1,2 ... etc.). To support multiple subscribers subscribing to a given topic, a prefix need to be set to the blob name in the storage container so each subscriber can lease and use their particular blob for storing checkpoint details. Proposed format for prefix is `dapr-topic-consumerID-`, qualifying the blob specifically for a particular topic and a particular subscriber (consumerID/consumerGroup).

- **TODO**  Support subscribing to multiple topics based on the incoming req.Topic field and the specified authentication mechanisms (see above)
- **TODO** Set a subscriber specific unique prefix to checkpoint blobs to enable multiple subscribers to the use the same storage container

### Entity Management

To enable multiple application replicas to read different partitions of topics, event hubs supports [consumer groups](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features#consumer-groups).
The current behaviour of the event hub is that for any subscribing application, the specified consumer group in the subscribe request must already be created and associated with the event hub.
For publishing to a newly created event hub there are no such restrictions and applications can directly publish data to the created event hub. Only for subscription of events from a newly created hub, the restriction is there where a particular subscriber's consumer group must be associated with an event hub before the subscriber can connect successfully to it. 

So entity management can be split into two parts
- **TODO** Creation of event hub if it does not exist with sane defaults
- **TODO** Creation of consumer group matching dapr `app-id` in the event hub

#### Creation of event hub

This can be achieved using the normal [azure-eventhubs-go](https://github.com/Azure/azure-event-hubs-go) client library itself. This is official Microsoft Azure event hubs client for Golang. This is being used already for publish and subscribe.

For connection string based authentication, the event hub namespace connection string is a requirement, and AAD should have `Manage` permissions in the event hub namespace.

#### Creation of consumer group

Unfortunately consumer group creation is not possible via the [azure-eventhubs-go](https://github.com/Azure/azure-event-hubs-go). It is only possible through the event hubs [management library](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-management-libraries).
Limitation of the event hubs management library is that it only supports AAD based authentication. Also additional details are necessary to create the consumer group. It requires the **subscription ID** and the **resource group name** where the event hub namespace is in addition to all other details. Permissions wise right now I have tested with client creations and specifying `Manage/Owner` permissions at event hub namespace level works. 

### Design in summary 
- Support both connection string and AAD based authentication 
- Support `partitionKey` for publish (this enables in-order processing)
- Fix code to support multiple subscribers for a given topic
- Add support for publishing and subscribing to multiple topics (event hubs)
- Have entity management as opt-in feature 
  - validate that the authentication mechanism is only AAD
  - in addition to creation of event hub, use the event hub management library to create correct consumer group for subscriber

### Component metadata
- **updated** `connectionString`: can be either event hub connection string or event hub namespace connection string (mandatory and mutually exclusive with eventHubNamespace)
- **new** `eventHubNamespace`: the event hub namespace name. (mandatory mutually exclusive with connectionString)
Metadata Mandatory for subscription
- **existing** `consumerID`: Set by dapr runtime. Used as the consumer group. Is the dapr app-id
- **existing** `storageAccountName`: name of the storage account to use
- **existing** `storageAccountKey`: access key for the storage account 
- **existing** `storageContainerName`: name of the storage container 
Metadata mandatory for entity management
- **new**`enableEntityManagement`: enable entity management (mutually exclusive with connectionString)
- **new** `resourceGroupName`: name of the resource group in which the event hub namespace is
- **new** `subscriptionID`: ID of the Azure subscription used
- **new** `messageRetentionInDays`: message retention amount 1-90[based on tiers](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-quotas) -  default 1 (optional)
- **new** `partitionCount`: partition count 1-1024[based on tiers](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-quotas) -  default 1 (optional)

### Valid configurations
By default all configurations support multiple subscribers (its a bug fix for an existing issue)
By default all configurations support `partitionKey` on publish (general enhancement)
#### Event hub namespace connection string given
- can publish and subscribe to multiple topics
- no entity management support
- all event hubs(topics) and associated consumer groups need to be created beforehand
#### Event hub connection string given 
- can publish and subscribe to this particular topic
- no entity management support
- topic and associated consumer groups need to be created beforehand
#### AAD based authentication 
- can publish and subscribe to multiple topics
- entity management support can be enabled
  - create topic on the fly on publish/subscribe if non-existent
  - create and associate consumer group with topic on subscribe if non-existent

### Concerns
- Entity management for event hub increases complexity of the code as well as moving more into management of infrastructure rather than only on the app integrations. 
- With the use of event processor host abstracting away partition and checkpoint management, support for batch receive is not possible in future. 
- Use of a management library requiring details on subscription ID and resource group name. 

Associated PR https://github.com/dapr/components-contrib/pull/1292

**Comment by mukundansundar** [comment]
@artursouza @yaron2 @CodeMonkeyLeet @berndverst Please chime in your thoughts on this.

**Comment by CodeMonkeyLeet** [comment]
A couple of questions and clarifications:
- What do items marked **TODO** mean? Are they specifically the set of items implemented in #1292?
- To clarify, there are no plans to add support for receiving on a specific `partitionKey`, only publish, correct? Might be useful to discuss why, as that's a functional parity difference with the bindings.
   - This is also relates to the implementation choice of only relying on EPH, which does not expose batch receive option; currently the bindings use the lower-level Hub object for allowing subscribing to a specific partition ID, and the Hub is also where batch receive options are exposed. Not useful to target for this round of rewrite, but useful to keep in mind that the EPH has other limitations.
- `ConsumerID` was previously undocumented as user settable, but if you provided it in config metadata, it looks like dapr did pass that value through. Probably want to account for that additional case.
- I agree that we should just not support entity management for the **Event hub namespace connection string given** case even though we could technically do hub creation without consumer group creation; simpler is better. 
- Clarifying my understanding of the valid configuration combinations (ignoring the separate bucket of metadata needed for subscription):
   | Configuration | Metadata | Validation |
   | --- | --- | --- |
   | Single Event Hub only (backwards compat) | Only `connectionString` to specific event hub | The presence of `eventHubNamespace` or any entity management metadata should be flagged as an error. |
   | Event Hub Namespace without entity management | Only `connectionString` to namespace | The presence of `eventHubNamespace` or any entity management metadata should be flagged as an error. | 
   | Event Hub Namespace without entity management (AAD auth) | `eventHubNamespace` with `enableEntityManagement` set to `false` | The presence of `connectionString` or any other entity management metadata should be flagged as an error. |
   | Event Hub Namespace with entity management (AAD auth) | `eventHubNamespace` with `enableEntityManagement` set to `true`, and `resourceGroup` and `subscriptionID` are both provided. | ? |
   
   For the validations in that last bucket:
   - Is it possible to simplify by inferring `enableEntityManagement` from the presence of both `resourceGroup` and `subscriptionID` instead to reduce the number of parameters to manage?
      - Also renaming the parameters to something more indicative of their usage and relationship to each other e.g. `entityManagementResourceGroup`, `entityManagementSubscriptionID`
      - Reduces validations down to either both are present or both are absent in the metadata.
    - Entity management may not use the `partitionCount` or `messageRetentionInDays` properties even if specified, since they are only relevant iff the component creates a new hub.
       - It should probably at least warn if an existing Hub is found that does not match the parameters specified, and the docs should clarify their intent. 
        - Is the default `partitionCount` of 1 a design decision or an inherited value from the underlying SDK? The Azure default is usually 2, with 1 available for Kafka-enabled namespaces using the Azure CLI as a reference.
        - For `messageRetentionInDays`, might be useful to explain why 1 day (e.g. it maximizes compatibility with namespaces, as basic tier must have it set to 1).
        - For either of these, it might be useful to check what underlying error is returned if the creation fails due to exceeding SKU tier limits ... it's likely folks are going to run into that and we might want to mitigate any confusion that it's an issue with the component.

**Comment by mukundansundar** [comment]
> A couple of questions and clarifications:
> 
> * What do items marked **TODO** mean? Are they specifically the set of items implemented in [rewrite EventHubs component #1292](https://github.com/dapr/components-contrib/pull/1292)?

Yes these are the ones that are not currently available and are done as part of the PR.

> * To clarify, there are no plans to add support for receiving on a specific `partitionKey`, only publish, correct? Might be useful to discuss why, as that's a functional parity difference with the bindings.
>   
>   * This is also relates to the implementation choice of only relying on EPH, which does not expose batch receive option; currently the bindings use the lower-level Hub object for allowing subscribing to a specific partition ID, and the Hub is also where batch receive options are exposed. Not useful to target for this round of rewrite, but useful to keep in mind that the EPH has other limitations.

As part of the rewrite is it a requirement to support subscribing to individual partitions? Taking Kafka as the Stable component for reference, the current Kafka component as far as I can see does not support consuming from specific partitions and does use the high level client to consume from topics.


> * `ConsumerID` was previously undocumented as user settable, but if you provided it in config metadata, it looks like dapr did pass that value through. Probably want to account for that additional case.

It is provided by the runtime itself, should not be set by user in general. 


> * I agree that we should just not support entity management for the **Event hub namespace connection string given** case even though we could technically do hub creation without consumer group creation; simpler is better.

>   
>   For the validations in that last bucket:
>   
>   * Is it possible to simplify by inferring `enableEntityManagement` from the presence of both `resourceGroup` and `subscriptionID` instead to reduce the number of parameters to manage?

Assuming that we do not support entity management without those, values (i.e. just plain event hub that we can publish to but cannot subscribe to), then yes we can infer entity management, but IMO having it specified explicitly helps the user to understand that entity management is being enabled and they do not need to dig through the logs to infer it.  

>     
>     * Also renaming the parameters to something more indicative of their usage and relationship to each other e.g. `entityManagementResourceGroup`, `entityManagementSubscriptionID`
>     * Reduces validations down to either both are present or both are absent in the metadata.
It does help with understanding why we have the variable but that is not what the variable value is. The variable is used for entityManagement in this scenario and there is nothing like an `entityManagementResourceGroup` or `entityManagementSubscriptionID`, I believe it might lead to confusion down the line. But if it is voted to use it that way, I can change it.


>   * Entity management may not use the `partitionCount` or `messageRetentionInDays` properties even if specified, since they are only relevant iff the component creates a new hub.
>     
>     * It should probably at least warn if an existing Hub is found that does not match the parameters specified, and the docs should clarify their intent.
Already the logs do warn if the hub exists and the values are ignored. Warning the user should be doable if needed.


>     * Is the default `partitionCount` of 1 a design decision or an inherited value from the underlying SDK? The Azure default is usually 2, with 1 available for Kafka-enabled namespaces using the Azure CLI as a reference.
Can be easily changed and it was a design decision, based on using Azure portal when I created the event hubs for testing, both the values were 1 by default.

>     * For `messageRetentionInDays`, might be useful to explain why 1 day (e.g. it maximizes compatibility with namespaces, as basic tier must have it set to 1).

Currently there are logs being written out if the default value is used, will add in a comment as to why in the code.

>     * For either of these, it might be useful to check what underlying error is returned if the creation fails due to exceeding SKU tier limits ... it's likely folks are going to run into that and we might want to mitigate any confusion that it's an issue with the component.

If the underlying component returns error, the error is wrapped with an operation specific error message and returned. So based on that and the underlying error, the user should be able to infer that it is not directly related to component.

**Comment by mukundansundar** [comment]
@yaron2 @artursouza  Can you review this design proposal?

**Comment by yaron2** [comment]
I would leave backwards compatibility out and not support an event hubs connection string, mainly because it causes a surprise behavior of ignoring the topic field which is supposed to be a required part of the API spec of pub/sub.

**Comment by mukundansundar** [comment]
I am ok with leaving backwards compatibility out if that is what is decided. 
//cc @yaron2 @artursouza

**Comment by artursouza** [comment]
Regarding your concerns:

"Entity management for event hub increases complexity of the code as well as moving more into management of infrastructure rather than only on the app integrations." - This is OK. Let's not worry about upgrading the management client yet. It can be a new PR later on.

"With the use of event processor host abstracting away partition and checkpoint management, support for batch receive is not possible in future." - It might be harder in the future but we can offer batching as a new metadata config.

"Use of a management library requiring details on subscription ID and resource group name." - Yes, only if entity management is enabled - which is not really "mandatory", so LGTM.

Another point is about backwards compatibility - although this is an Alpha component, I think the old code should remain to avoid breaking existing users and we can put a notice to remove it in the next release or so. In other words, this rewrite should be a new version of this component (IMO).

**Comment by mukundansundar** [comment]
I have reopened the PR #1292. Please review @yaron2 @artursouza.

**Comment by mukundansundar** [comment]
will close once conformance tests are fixed

**Comment by artursouza** [comment]
Code is merged.
